import type { ModelDefinition } from "@/models.js";

export const alibabaModels = [
	{
		id: "qwen-max",
		name: "Qwen Max",
		description: "Alibaba's flagship Qwen model with vision and tool support.",
		family: "alibaba",
		releasedAt: new Date("2025-09-05"),
		providers: [
			{
				test: "skip",
				providerId: "alibaba",
				modelName: "qwen-max",
				discount: 0.2,
				inputPrice: 1.6 / 1e6,
				outputPrice: 6.4 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 32000,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen-max-latest",
		name: "Qwen Max Latest",
		description: "Latest Qwen Max with enhanced capabilities.",
		family: "alibaba",
		releasedAt: new Date("2025-01-25"),
		providers: [
			{
				test: "skip",
				providerId: "alibaba",
				modelName: "qwen-max-latest",
				discount: 0.2,
				inputPrice: 1.6 / 1e6,
				outputPrice: 6.4 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 32000,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen-plus",
		name: "Qwen Plus",
		description: "Mid-tier Qwen model balancing speed and capability.",
		family: "alibaba",
		releasedAt: new Date("2025-01-25"),
		providers: [
			{
				providerId: "alibaba",
				modelName: "qwen-plus",
				discount: 0.2,
				inputPrice: 0.4 / 1e6,
				outputPrice: 1.2 / 1e6,
				cachedInputPrice: 0.08 / 1e6,
				pricingTiers: [
					{
						name: "Up to 256K",
						upToTokens: 256000,
						inputPrice: 0.4 / 1e6,
						outputPrice: 1.2 / 1e6,
						cachedInputPrice: 0.08 / 1e6,
					},
					{
						name: "Over 256K",
						upToTokens: Infinity,
						inputPrice: 1.2 / 1e6,
						outputPrice: 3.6 / 1e6,
						cachedInputPrice: 0.24 / 1e6,
					},
				],
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 32000,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen-plus-latest",
		name: "Qwen Plus Latest",
		description: "Updated Qwen Plus with extended context support.",
		family: "alibaba",
		releasedAt: new Date("2024-09-09"),
		providers: [
			{
				providerId: "alibaba",
				modelName: "qwen-plus-latest",
				discount: 0.2,
				inputPrice: 0.4 / 1e6,
				outputPrice: 1.2 / 1e6,
				cachedInputPrice: 0.08 / 1e6,
				pricingTiers: [
					{
						name: "Up to 256K",
						upToTokens: 256000,
						inputPrice: 0.4 / 1e6,
						outputPrice: 1.2 / 1e6,
						cachedInputPrice: 0.08 / 1e6,
					},
					{
						name: "Over 256K",
						upToTokens: Infinity,
						inputPrice: 1.2 / 1e6,
						outputPrice: 3.6 / 1e6,
						cachedInputPrice: 0.24 / 1e6,
					},
				],
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: 32000,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen-flash",
		name: "Qwen Flash",
		description: "Fast, cost-effective Qwen for high-volume tasks.",
		family: "alibaba",
		releasedAt: new Date("2024-09-09"),
		providers: [
			{
				providerId: "alibaba",
				modelName: "qwen-flash",
				discount: 0.2,
				inputPrice: 0.05 / 1e6,
				outputPrice: 0.4 / 1e6,
				cachedInputPrice: 0.01 / 1e6,
				pricingTiers: [
					{
						name: "Up to 256K",
						upToTokens: 256000,
						inputPrice: 0.05 / 1e6,
						outputPrice: 0.4 / 1e6,
						cachedInputPrice: 0.01 / 1e6,
					},
					{
						name: "Over 256K",
						upToTokens: Infinity,
						inputPrice: 0.25 / 1e6,
						outputPrice: 2.0 / 1e6,
						cachedInputPrice: 0.05 / 1e6,
					},
				],
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: 32000,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen-omni-turbo",
		name: "Qwen Omni Turbo",
		description: "Multimodal Qwen with vision support.",
		family: "alibaba",
		releasedAt: new Date("2025-03-26"),
		providers: [
			{
				providerId: "alibaba",
				modelName: "qwen-omni-turbo",
				discount: 0.2,
				inputPrice: 0.2 / 1e6,
				outputPrice: 0.8 / 1e6,
				requestPrice: 0,
				contextSize: 32768,
				maxOutput: 8192,
				streaming: true,
				vision: true,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen-turbo",
		name: "Qwen Turbo",
		description: "Fastest Qwen model for quick responses.",
		family: "alibaba",
		releasedAt: new Date("2025-02-01"),
		providers: [
			{
				providerId: "alibaba",
				modelName: "qwen-turbo",
				discount: 0.2,
				inputPrice: 0.05 / 1e6,
				outputPrice: 0.2 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen3-coder-plus",
		name: "Qwen3 Coder Plus",
		description: "Advanced Qwen for code generation.",
		family: "alibaba",
		releasedAt: new Date("2025-09-23"),
		providers: [
			{
				test: "skip",
				providerId: "kiwillm-qwen",
				modelName: "qwen3-coder-plus",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: 66000,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "alibaba",
				modelName: "qwen3-coder-plus",
				discount: 0.2,
				inputPrice: 6 / 1e6,
				outputPrice: 60 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: 66000,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen-qwq-32b",
		name: "Qwen QwQ 32B",
		description: "Qwen 32B reasoning model.",
		family: "alibaba",
		releasedAt: new Date("2025-03-01"),
		providers: [
			{
				providerId: "nebius",
				modelName: "Qwen/QwQ-32B",
				inputPrice: 0.15 / 1e6,
				outputPrice: 0.45 / 1e6,
				requestPrice: 0,
				contextSize: 32768,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
				deactivatedAt: new Date("2025-11-03"),
			},
		],
	},
	{
		id: "qwen3-235b-a22b-instruct-2507",
		name: "Qwen3 235B A22B Instruct 2507",
		description: "Large Qwen 3 MoE instruction model.",
		family: "alibaba",
		releasedAt: new Date("2025-07-21"),
		providers: [
			{
				providerId: "nebius",
				stability: "unstable",
				modelName: "Qwen/Qwen3-235B-A22B-Instruct-2507",
				inputPrice: 0.2 / 1e6,
				outputPrice: 0.6 / 1e6,
				requestPrice: 0,
				contextSize: 262000,
				maxOutput: 8192,
				reasoning: false,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
			{
				// Cerebras: FP16/FP8 (weights only)
				providerId: "cerebras",
				test: "skip",
				modelName: "qwen-3-235b-a22b-instruct-2507",
				inputPrice: 0.6 / 1e6,
				outputPrice: 1.2 / 1e6,
				requestPrice: 0,
				contextSize: 262000,
				maxOutput: 8192,
				reasoning: false,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
				supportedParameters: [
					"temperature",
					"max_tokens",
					"top_p",
					"response_format",
					"tools",
					"tool_choice",
				],
			},
			{
				providerId: "novita",
				modelName: "qwen/qwen3-235b-a22b-instruct-2507",
				inputPrice: 0.09 / 1e6,
				outputPrice: 0.58 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 16384,
				reasoning: false,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen3-235b-a22b-thinking-2507",
		name: "Qwen3 235B A22B Thinking 2507",
		description: "Qwen 3 MoE with reasoning capabilities.",
		family: "alibaba",
		releasedAt: new Date("2025-07-25"),
		providers: [
			{
				providerId: "nebius",
				modelName: "Qwen/Qwen3-235B-A22B-Thinking-2507",
				inputPrice: 0.2 / 1e6,
				outputPrice: 0.6 / 1e6,
				requestPrice: 0,
				contextSize: 262000,
				maxOutput: 8192,
				reasoning: true,
				streaming: true,
				vision: false,
				tools: true,
				stability: "unstable",
				jsonOutput: true,
			},
			{
				providerId: "novita",
				modelName: "qwen/qwen3-235b-a22b-thinking-2507",
				inputPrice: 0.3 / 1e6,
				outputPrice: 3 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 32768,
				reasoning: false,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: false,
			},
		],
	},
	{
		id: "qwen3-235b-a22b-fp8",
		name: "Qwen3 235B A22B FP8",
		description: "Qwen 3 235B MoE with FP8 quantization.",
		family: "alibaba",
		releasedAt: new Date("2025-04-28"),
		providers: [
			{
				providerId: "novita",
				modelName: "qwen/qwen3-235b-a22b-fp8",
				inputPrice: 0.2 / 1e6,
				outputPrice: 0.8 / 1e6,
				requestPrice: 0,
				contextSize: 40960,
				maxOutput: 20000,
				reasoning: false,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen3-14b",
		name: "Qwen3 14B",
		description: "Mid-size Qwen 3 model.",
		family: "alibaba",
		releasedAt: new Date("2025-04-28"),
		providers: [
			{
				providerId: "nebius",
				modelName: "Qwen/Qwen3-14B",
				inputPrice: 0.08 / 1e6,
				outputPrice: 0.24 / 1e6,
				requestPrice: 0,
				contextSize: 32768,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
				deactivatedAt: new Date("2025-11-03"),
			},
		],
	},
	{
		id: "qwen3-32b",
		name: "Qwen3 32B",
		description: "Mid-size Qwen 3 model.",
		family: "alibaba",
		releasedAt: new Date("2025-04-28"),
		providers: [
			{
				providerId: "nebius",
				modelName: "Qwen/Qwen3-32B",
				inputPrice: 0.1 / 1e6,
				outputPrice: 0.3 / 1e6,
				requestPrice: 0,
				contextSize: 32768,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
			{
				// Cerebras: FP16
				providerId: "cerebras",
				modelName: "qwen-3-32b",
				inputPrice: 0.4 / 1e6,
				outputPrice: 0.8 / 1e6,
				requestPrice: 0,
				contextSize: 32768,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
				supportedParameters: [
					"temperature",
					"max_tokens",
					"top_p",
					"response_format",
					"tools",
					"tool_choice",
				],
				deactivatedAt: new Date("2026-02-16"),
			},
		],
	},
	{
		id: "qwen3-30b-a3b",
		name: "Qwen3 30B A3B",
		description: "Mid-size Qwen 3 MoE model.",
		family: "alibaba",
		releasedAt: new Date("2025-04-28"),
		providers: [
			{
				providerId: "nebius",
				modelName: "Qwen/Qwen3-30B-A3B",
				inputPrice: 0.1 / 1e6,
				outputPrice: 0.3 / 1e6,
				requestPrice: 0,
				contextSize: 32768,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
				deactivatedAt: new Date("2025-11-03"),
			},
		],
	},
	{
		id: "qwen25-coder-7b",
		name: "Qwen2.5 Coder 7B",
		description: "Qwen 2.5 code model, 7B size.",
		family: "alibaba",
		releasedAt: new Date("2024-09-19"),
		providers: [
			{
				providerId: "nebius",
				modelName: "Qwen/Qwen2.5-Coder-7B-fast",
				inputPrice: 0.01 / 1e6,
				outputPrice: 0.03 / 1e6,
				requestPrice: 0,
				contextSize: 32768,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen25-32b-instruct",
		name: "Qwen2.5 32B Instruct",
		description: "Qwen 2.5 instruction model, 32B size.",
		family: "alibaba",
		releasedAt: new Date("2024-09-19"),
		providers: [
			{
				providerId: "nebius",
				modelName: "Qwen/Qwen2.5-32B-Instruct",
				inputPrice: 0.06 / 1e6,
				outputPrice: 0.2 / 1e6,
				requestPrice: 0,
				contextSize: 32768,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
				deactivatedAt: new Date("2025-09-10"),
			},
		],
	},
	{
		id: "qwen25-72b-instruct",
		name: "Qwen2.5 72B Instruct",
		description: "Qwen 2.5 instruction model, 72B size.",
		family: "alibaba",
		releasedAt: new Date("2024-09-19"),
		providers: [
			{
				providerId: "nebius",
				modelName: "Qwen/Qwen2.5-72B-Instruct",
				inputPrice: 0.13 / 1e6,
				outputPrice: 0.4 / 1e6,
				requestPrice: 0,
				contextSize: 32768,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
				deactivatedAt: new Date("2025-11-03"),
			},
		],
	},
	{
		id: "qwen2-vl-72b-instruct",
		name: "Qwen2 VL 72B Instruct",
		description: "Vision-language Qwen 2 model, 72B size.",
		family: "alibaba",
		releasedAt: new Date("2024-09-19"),
		providers: [
			{
				providerId: "nebius",
				modelName: "Qwen/Qwen2-VL-72B-Instruct",
				inputPrice: 0.13 / 1e6,
				outputPrice: 0.4 / 1e6,
				requestPrice: 0,
				contextSize: 32768,
				maxOutput: 8192,
				streaming: true,
				vision: true,
				tools: false,
				jsonOutput: true,
				deactivatedAt: new Date("2025-09-10"),
			},
		],
	},
	{
		id: "qwen2-5-vl-72b-instruct",
		name: "Qwen2.5 VL 72B Instruct",
		description: "Vision-language Qwen 2.5 model, 72B size.",
		family: "alibaba",
		releasedAt: new Date("2025-01-26"),
		providers: [
			{
				providerId: "nebius",
				modelName: "Qwen/Qwen2.5-VL-72B-Instruct",
				inputPrice: 0.13 / 1e6,
				outputPrice: 0.4 / 1e6,
				requestPrice: 0,
				contextSize: 32768,
				maxOutput: 8192,
				streaming: true,
				vision: true,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen3-vl-8b-instruct",
		name: "Qwen3 VL 8B Instruct",
		description: "Vision-language Qwen 3 model, 8B size.",
		family: "alibaba",
		releasedAt: new Date("2025-10-14"),
		providers: [
			{
				providerId: "novita",
				modelName: "qwen/qwen3-vl-8b-instruct",
				inputPrice: 0.08 / 1e6,
				outputPrice: 0.5 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 8192,
				streaming: true,
				vision: true,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen3-coder-480b-a35b-instruct",
		name: "Qwen3 Coder 480B A35B Instruct",
		description: "Code-specialized Qwen 3 MoE, 480B size.",
		family: "alibaba",
		releasedAt: new Date("2025-01-31"),
		providers: [
			{
				providerId: "nebius",
				modelName: "Qwen/Qwen3-Coder-480B-A35B-Instruct",
				inputPrice: 0.4 / 1e6,
				outputPrice: 1.8 / 1e6,
				requestPrice: 0,
				contextSize: 262000,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
			{
				providerId: "novita",
				modelName: "qwen/qwen3-coder-480b-a35b-instruct",
				inputPrice: 0.3 / 1e6,
				outputPrice: 1.3 / 1e6,
				requestPrice: 0,
				contextSize: 262144,
				maxOutput: 65536,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
			{
				providerId: "canopywave",
				deactivatedAt: new Date("2026-02-01"),
				modelName: "qwen/qwen3-coder-480b-a35b-instruct",
				inputPrice: 0.3 / 1e6,
				outputPrice: 1.3 / 1e6,
				discount: 0.3,
				requestPrice: 0,
				contextSize: 262144,
				maxOutput: 65536,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen3-coder-30b-a3b-instruct",
		name: "Qwen3 Coder 30B A3B Instruct",
		description: "Code-specialized Qwen 3 MoE, 30B size.",
		family: "alibaba",
		releasedAt: new Date("2025-07-31"),
		providers: [
			{
				providerId: "nebius",
				modelName: "Qwen/Qwen3-Coder-30B-A3B-Instruct",
				inputPrice: 0.1 / 1e6,
				outputPrice: 0.3 / 1e6,
				requestPrice: 0,
				contextSize: 262000,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
			{
				providerId: "novita",
				modelName: "qwen/qwen3-coder-30b-a3b-instruct",
				inputPrice: 0.07 / 1e6,
				outputPrice: 0.27 / 1e6,
				requestPrice: 0,
				contextSize: 160000,
				maxOutput: 32768,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen3-30b-a3b-instruct-2507",
		name: "Qwen3 30B A3B Instruct 2507",
		description: "Qwen 3 MoE instruction model, July 2025.",
		family: "alibaba",
		releasedAt: new Date("2025-07-30"),
		providers: [
			{
				providerId: "nebius",
				modelName: "Qwen/Qwen3-30B-A3B-Instruct-2507",
				inputPrice: 0.1 / 1e6,
				outputPrice: 0.3 / 1e6,
				requestPrice: 0,
				contextSize: 262000,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen3-30b-a3b-thinking-2507",
		name: "Qwen3 30B A3B Thinking 2507",
		description: "Qwen 3 MoE with reasoning, July 2025.",
		family: "alibaba",
		releasedAt: new Date("2025-07-30"),
		providers: [
			{
				providerId: "nebius",
				modelName: "Qwen/Qwen3-30B-A3B-Thinking-2507",
				inputPrice: 0.1 / 1e6,
				outputPrice: 0.3 / 1e6,
				requestPrice: 0,
				contextSize: 262000,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
				reasoning: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen-vl-max",
		name: "Qwen VL Max",
		description: "Vision-language Qwen flagship model.",
		family: "alibaba",
		releasedAt: new Date("2025-02-01"),
		providers: [
			{
				providerId: "alibaba",
				modelName: "qwen-vl-max",
				discount: 0.2,
				inputPrice: 0.8 / 1e6,
				outputPrice: 3.2 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 32000,
				streaming: true,
				vision: true,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen-vl-plus",
		name: "Qwen VL Plus",
		description: "Vision-language Qwen mid-tier model.",
		family: "alibaba",
		releasedAt: new Date("2025-02-05"),
		providers: [
			{
				providerId: "alibaba",
				modelName: "qwen-vl-plus",
				discount: 0.2,
				inputPrice: 0.21 / 1e6,
				outputPrice: 0.64 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 32000,
				streaming: true,
				vision: true,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen3-next-80b-a3b-thinking",
		name: "Qwen3 Next 80B A3B Thinking",
		description: "Preview Qwen 3 Next with reasoning.",
		family: "alibaba",
		releasedAt: new Date("2025-09-10"),
		providers: [
			{
				providerId: "alibaba",
				stability: "unstable",
				modelName: "qwen3-next-80b-a3b-thinking",
				discount: 0.2,
				inputPrice: 0.5 / 1e6,
				outputPrice: 6 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 32768,
				reasoning: true,
				reasoningOutput: "omit",
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: false,
			},
			{
				providerId: "novita",
				modelName: "qwen/qwen3-next-80b-a3b-thinking",
				inputPrice: 0.15 / 1e6,
				outputPrice: 1.5 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 32768,
				reasoning: true,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: false,
			},
		],
	},
	{
		id: "qwen3-next-80b-a3b-instruct",
		name: "Qwen3 Next 80B A3B Instruct",
		description: "Preview Qwen 3 Next instruction model.",
		family: "alibaba",
		releasedAt: new Date("2025-09-10"),
		providers: [
			{
				providerId: "alibaba",
				modelName: "qwen3-next-80b-a3b-instruct",
				discount: 0.2,
				inputPrice: 0.5 / 1e6,
				outputPrice: 2 / 1e6,
				requestPrice: 0,
				contextSize: 129024,
				maxOutput: 32768,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
			{
				providerId: "novita",
				modelName: "qwen/qwen3-next-80b-a3b-instruct",
				inputPrice: 0.15 / 1e6,
				outputPrice: 1.5 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 32768,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen3-max",
		name: "Qwen3 Max",
		description: "Top-tier Qwen 3 with reasoning and vision support.",
		family: "alibaba",
		releasedAt: new Date("2025-09-24"),
		providers: [
			{
				test: "skip",
				providerId: "alibaba",
				modelName: "qwen3-max-preview",
				discount: 0.2,
				inputPrice: 3 / 1e6,
				outputPrice: 15 / 1e6,
				cachedInputPrice: 0.6 / 1e6,
				requestPrice: 0,
				contextSize: 256000,
				maxOutput: 32800,
				reasoning: true,
				reasoningOutput: "omit",
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
			{
				providerId: "novita",
				modelName: "qwen/qwen3-max",
				inputPrice: 0.845 / 1e6,
				outputPrice: 3.38 / 1e6,
				requestPrice: 0,
				contextSize: 262144,
				maxOutput: 65536,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen3-coder",
		name: "Qwen3 Coder",
		description: "General Qwen 3 coding model.",
		family: "alibaba",
		releasedAt: new Date("2025-07-23"),
		providers: [
			{
				providerId: "canopywave",
				deactivatedAt: new Date("2026-02-01"),
				modelName: "qwen/qwen3-coder",
				inputPrice: 0.22 / 1e6,
				outputPrice: 0.95 / 1e6,
				discount: 0.3,
				requestPrice: 0,
				contextSize: 262000,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen3-vl-30b-a3b-instruct",
		name: "Qwen3 VL 30B A3B Instruct",
		description: "Vision-language Qwen 3 MoE model, 30B size.",
		family: "alibaba",
		releasedAt: new Date("2025-10-05"),
		providers: [
			{
				providerId: "novita",
				modelName: "qwen/qwen3-vl-30b-a3b-instruct",
				inputPrice: 0.2 / 1e6,
				outputPrice: 0.7 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 32768,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: false,
				supportedParameters: [
					"temperature",
					"max_tokens",
					"top_p",
					"frequency_penalty",
					"response_format",
					"tools",
					"tool_choice",
				],
			},
		],
	},
	{
		id: "qwen3-vl-30b-a3b-thinking",
		name: "Qwen3 VL 30B A3B Thinking",
		description: "Vision-language Qwen 3 MoE with reasoning capabilities.",
		family: "alibaba",
		releasedAt: new Date("2025-10-11"),
		providers: [
			{
				providerId: "novita",
				modelName: "qwen/qwen3-vl-30b-a3b-thinking",
				inputPrice: 0.2 / 1e6,
				outputPrice: 1 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 32768,
				reasoning: true,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen3-32b-fp8",
		name: "Qwen3 32B FP8",
		description: "Qwen 3 32B with FP8 quantization.",
		family: "alibaba",
		releasedAt: new Date("2025-04-28"),
		providers: [
			{
				providerId: "novita",
				modelName: "qwen/qwen3-32b-fp8",
				inputPrice: 0.1 / 1e6,
				outputPrice: 0.45 / 1e6,
				requestPrice: 0,
				contextSize: 40960,
				maxOutput: 20000,
				reasoning: false,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: false,
			},
		],
	},
	{
		id: "qwen3-30b-a3b-fp8",
		name: "Qwen3 30B A3B FP8",
		description: "Qwen 3 30B MoE with FP8 quantization.",
		family: "alibaba",
		releasedAt: new Date("2025-04-28"),
		providers: [
			{
				providerId: "novita",
				modelName: "qwen/qwen3-30b-a3b-fp8",
				inputPrice: 0.09 / 1e6,
				outputPrice: 0.45 / 1e6,
				requestPrice: 0,
				contextSize: 40960,
				maxOutput: 20000,
				reasoning: false,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: false,
			},
		],
	},
	{
		id: "qwen3-4b-fp8",
		name: "Qwen3 4B FP8",
		description: "Lightweight Qwen 3 4B with FP8 quantization.",
		family: "alibaba",
		releasedAt: new Date("2025-04-28"),
		providers: [
			{
				providerId: "novita",
				modelName: "qwen/qwen3-4b-fp8",
				inputPrice: 0.03 / 1e6,
				outputPrice: 0.03 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: 20000,
				reasoning: false,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: false,
			},
		],
	},
	{
		id: "qwen35-397b-a17b",
		name: "Qwen3.5 397B A17B",
		description:
			"Native multimodal MoE model with 397B total / 17B active parameters, reasoning, and agent capabilities.",
		family: "alibaba",
		releasedAt: new Date("2026-02-16"),
		providers: [
			{
				providerId: "alibaba",
				modelName: "qwen3.5-397b-a17b",
				discount: 0.2,
				inputPrice: 0.6 / 1e6,
				outputPrice: 3.6 / 1e6,
				requestPrice: 0,
				contextSize: 262144,
				maxOutput: 65536,
				reasoning: true,
				streaming: true,
				vision: true,
				tools: true,
				webSearch: true,
				webSearchPrice: 0.01,
				jsonOutput: true,
			},
			{
				providerId: "novita",
				modelName: "qwen/qwen3.5-397b-a17b",
				inputPrice: 0.6 / 1e6,
				outputPrice: 3.6 / 1e6,
				requestPrice: 0,
				contextSize: 262144,
				maxOutput: 64000,
				reasoning: true,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen-image-plus",
		name: "Qwen Image Plus",
		description:
			"Alibaba's Qwen Image Plus model for text-to-image generation with excellent text rendering capabilities.",
		family: "alibaba",
		output: ["text", "image"],
		releasedAt: new Date("2025-08-04"),
		providers: [
			{
				test: "skip",
				providerId: "alibaba",
				modelName: "qwen-image-plus",
				discount: 0.2,
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0.03,
				contextSize: 2000,
				maxOutput: 4096,
				streaming: false,
				vision: false,
				tools: false,
				jsonOutput: false,
				imageGenerations: true,
			},
		],
	},
	{
		id: "qwen-image-max",
		name: "Qwen Image Max",
		description:
			"Alibaba's flagship Qwen Image Max model for highest quality text-to-image generation.",
		family: "alibaba",
		output: ["text", "image"],
		releasedAt: new Date("2025-08-04"),
		providers: [
			{
				test: "skip",
				providerId: "alibaba",
				modelName: "qwen-image-max",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0.075,
				contextSize: 2000,
				maxOutput: 4096,
				streaming: false,
				vision: false,
				tools: false,
				jsonOutput: false,
				imageGenerations: true,
			},
		],
	},
	{
		id: "qwen-image",
		name: "Qwen Image",
		description:
			"Alibaba's Qwen Image model for text-to-image generation with excellent text rendering capabilities.",
		family: "alibaba",
		output: ["text", "image"],
		releasedAt: new Date("2025-08-04"),
		providers: [
			{
				test: "skip",
				providerId: "alibaba",
				modelName: "qwen-image",
				discount: 0.2,
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0.035,
				contextSize: 2000,
				maxOutput: 4096,
				streaming: false,
				vision: false,
				tools: false,
				jsonOutput: false,
				imageGenerations: true,
			},
		],
	},
	{
		id: "qwen-image-max-2025-12-30",
		name: "Qwen Image Max 2025-12-30",
		description:
			"Alibaba's Qwen 2025-12-30 Image model for text-to-image generation with excellent text rendering capabilities.",
		family: "alibaba",
		output: ["text", "image"],
		releasedAt: new Date("2025-12-31"),
		providers: [
			{
				test: "skip",
				providerId: "alibaba",
				modelName: "qwen-image-max-2025-12-30",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0.075,
				contextSize: 2000,
				maxOutput: 4096,
				streaming: false,
				vision: false,
				tools: false,
				jsonOutput: false,
				imageGenerations: true,
			},
		],
	},
	{
		id: "qwq-plus",
		name: "QwQ Plus",
		description:
			"Alibaba's reasoning model with enhanced math and code capabilities.",
		family: "alibaba",
		releasedAt: new Date("2025-03-06"),
		providers: [
			{
				providerId: "alibaba",
				modelName: "qwq-plus",
				discount: 0.2,
				inputPrice: 0.8 / 1e6,
				outputPrice: 2.4 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 8192,
				reasoning: true,
				reasoningOutput: "omit",
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: false,
			},
		],
	},
	{
		id: "qwen-coder-plus",
		name: "Qwen Coder Plus",
		description: "Alibaba's code-specialized model based on Qwen2.5.",
		family: "alibaba",
		releasedAt: new Date("2024-09-18"),
		providers: [
			{
				test: "skip",
				providerId: "alibaba",
				modelName: "qwen-coder-plus",
				discount: 0.2,
				inputPrice: 1.0 / 1e6,
				outputPrice: 5.0 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen3-coder-flash",
		name: "Qwen3 Coder Flash",
		description: "Fast, cost-effective Qwen 3 model for code generation.",
		family: "alibaba",
		releasedAt: new Date("2025-07-22"),
		providers: [
			{
				providerId: "kiwillm-qwen",
				modelName: "qwen3-coder-flash",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 262144,
				maxOutput: 65536,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
			{
				providerId: "alibaba",
				modelName: "qwen3-coder-flash",
				discount: 0.2,
				inputPrice: 0.3 / 1e6,
				outputPrice: 1.5 / 1e6,
				cachedInputPrice: 0.06 / 1e6,
				pricingTiers: [
					{
						name: "Up to 32K",
						upToTokens: 32000,
						inputPrice: 0.3 / 1e6,
						outputPrice: 1.5 / 1e6,
						cachedInputPrice: 0.06 / 1e6,
					},
					{
						name: "32K-128K",
						upToTokens: 128000,
						inputPrice: 0.5 / 1e6,
						outputPrice: 2.5 / 1e6,
						cachedInputPrice: 0.1 / 1e6,
					},
					{
						name: "128K-256K",
						upToTokens: 256000,
						inputPrice: 0.8 / 1e6,
						outputPrice: 4.0 / 1e6,
						cachedInputPrice: 0.16 / 1e6,
					},
					{
						name: "Over 256K",
						upToTokens: Infinity,
						inputPrice: 1.6 / 1e6,
						outputPrice: 9.6 / 1e6,
						cachedInputPrice: 0.32 / 1e6,
					},
				],
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: 65536,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen3-vl-plus",
		name: "Qwen3 VL Plus",
		description: "Qwen 3 vision-language model with balanced performance.",
		family: "alibaba",
		releasedAt: new Date("2025-09-23"),
		providers: [
			{
				providerId: "alibaba",
				modelName: "qwen3-vl-plus",
				discount: 0.2,
				inputPrice: 0.2 / 1e6,
				outputPrice: 1.6 / 1e6,
				cachedInputPrice: 0.04 / 1e6,
				pricingTiers: [
					{
						name: "Up to 32K",
						upToTokens: 32000,
						inputPrice: 0.2 / 1e6,
						outputPrice: 1.6 / 1e6,
						cachedInputPrice: 0.04 / 1e6,
					},
					{
						name: "32K-128K",
						upToTokens: 128000,
						inputPrice: 0.3 / 1e6,
						outputPrice: 2.4 / 1e6,
						cachedInputPrice: 0.06 / 1e6,
					},
					{
						name: "Over 128K",
						upToTokens: Infinity,
						inputPrice: 0.6 / 1e6,
						outputPrice: 4.8 / 1e6,
						cachedInputPrice: 0.12 / 1e6,
					},
				],
				requestPrice: 0,
				contextSize: 262144,
				maxOutput: 32768,
				streaming: true,
				vision: true,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen3-vl-flash",
		name: "Qwen3 VL Flash",
		description: "Fast Qwen 3 vision-language model for quick image tasks.",
		family: "alibaba",
		releasedAt: new Date("2025-10-15"),
		providers: [
			{
				providerId: "alibaba",
				modelName: "qwen3-vl-flash",
				discount: 0.2,
				inputPrice: 0.05 / 1e6,
				outputPrice: 0.4 / 1e6,
				cachedInputPrice: 0.01 / 1e6,
				pricingTiers: [
					{
						name: "Up to 32K",
						upToTokens: 32000,
						inputPrice: 0.05 / 1e6,
						outputPrice: 0.4 / 1e6,
						cachedInputPrice: 0.01 / 1e6,
					},
					{
						name: "32K-128K",
						upToTokens: 128000,
						inputPrice: 0.075 / 1e6,
						outputPrice: 0.6 / 1e6,
						cachedInputPrice: 0.015 / 1e6,
					},
					{
						name: "Over 128K",
						upToTokens: Infinity,
						inputPrice: 0.12 / 1e6,
						outputPrice: 0.96 / 1e6,
						cachedInputPrice: 0.024 / 1e6,
					},
				],
				requestPrice: 0,
				contextSize: 262144,
				maxOutput: 32768,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen3-vl-235b-a22b-instruct",
		name: "Qwen3 VL 235B A22B Instruct",
		description: "Large Qwen 3 MoE vision-language instruction model.",
		family: "alibaba",
		releasedAt: new Date("2025-09-23"),
		providers: [
			{
				providerId: "alibaba",
				modelName: "qwen3-vl-235b-a22b-instruct",
				discount: 0.2,
				inputPrice: 0.5 / 1e6,
				outputPrice: 2.0 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 32768,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
			{
				providerId: "novita",
				modelName: "qwen/qwen3-vl-235b-a22b-instruct",
				inputPrice: 0.3 / 1e6,
				outputPrice: 1.5 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 32768,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen3-vl-235b-a22b-thinking",
		name: "Qwen3 VL 235B A22B Thinking",
		description:
			"Large Qwen 3 MoE vision-language model with reasoning capabilities.",
		family: "alibaba",
		releasedAt: new Date("2025-09-23"),
		providers: [
			{
				providerId: "alibaba",
				modelName: "qwen3-vl-235b-a22b-thinking",
				discount: 0.2,
				inputPrice: 0.5 / 1e6,
				outputPrice: 2.0 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 32768,
				reasoning: true,
				reasoningOutput: "omit",
				streaming: true,
				vision: true,
				tools: false,
				jsonOutput: false,
			},
			{
				providerId: "novita",
				modelName: "qwen/qwen3-vl-235b-a22b-thinking",
				inputPrice: 0.98 / 1e6,
				outputPrice: 3.95 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 32768,
				reasoning: true,
				streaming: true,
				vision: true,
				tools: false,
				jsonOutput: false,
			},
		],
	},
	{
		id: "qwen2-5-vl-32b-instruct",
		name: "Qwen2.5 VL 32B Instruct",
		description: "Vision-language Qwen 2.5 model, 32B size.",
		family: "alibaba",
		releasedAt: new Date("2025-02-19"),
		providers: [
			{
				test: "skip",
				providerId: "alibaba",
				modelName: "qwen2.5-vl-32b-instruct",
				discount: 0.2,
				inputPrice: 1.4 / 1e6,
				outputPrice: 4.2 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 32768,
				streaming: true,
				vision: true,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen3-max-2026-01-23",
		name: "Qwen3 Max 2026-01-23",
		description:
			"Latest Qwen 3 flagship model with integrated thinking mode and tool support.",
		family: "alibaba",
		releasedAt: new Date("2026-01-23"),
		providers: [
			{
				test: "skip",
				providerId: "alibaba",
				modelName: "qwen3-max-2026-01-23",
				discount: 0.2,
				inputPrice: 1.2 / 1e6,
				outputPrice: 6.0 / 1e6,
				cachedInputPrice: 0.24 / 1e6,
				pricingTiers: [
					{
						name: "Up to 32K",
						upToTokens: 32000,
						inputPrice: 1.2 / 1e6,
						outputPrice: 6.0 / 1e6,
						cachedInputPrice: 0.24 / 1e6,
					},
					{
						name: "32K-128K",
						upToTokens: 128000,
						inputPrice: 2.4 / 1e6,
						outputPrice: 12.0 / 1e6,
						cachedInputPrice: 0.48 / 1e6,
					},
					{
						name: "Over 128K",
						upToTokens: Infinity,
						inputPrice: 3.0 / 1e6,
						outputPrice: 15.0 / 1e6,
						cachedInputPrice: 0.6 / 1e6,
					},
				],
				requestPrice: 0,
				contextSize: 262144,
				maxOutput: 65536,
				reasoning: true,
				reasoningOutput: "omit",
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "qwen-image-edit-plus",
		name: "Qwen Image Edit Plus",
		description: "Alibaba's image editing model for modifying existing images.",
		family: "alibaba",
		output: ["text", "image"],
		imageInputRequired: true,
		releasedAt: new Date("2025-08-19"),
		providers: [
			{
				test: "skip",
				providerId: "alibaba",
				modelName: "qwen-image-edit-plus",
				discount: 0.2,
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0.04,
				contextSize: 2000,
				maxOutput: 4096,
				streaming: false,
				vision: true,
				tools: false,
				jsonOutput: false,
				imageGenerations: true,
			},
		],
	},
	{
		id: "qwen-image-edit-max",
		name: "Qwen Image Edit Max",
		description:
			"Alibaba's flagship image editing model for high-quality image modifications.",
		family: "alibaba",
		output: ["text", "image"],
		imageInputRequired: true,
		releasedAt: new Date("2026-01-16"),
		providers: [
			{
				test: "skip",
				providerId: "alibaba",
				modelName: "qwen-image-edit-max",
				discount: 0.2,
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0.08,
				contextSize: 2000,
				maxOutput: 4096,
				streaming: false,
				vision: true,
				tools: false,
				jsonOutput: false,
				imageGenerations: true,
			},
		],
	},
] as const satisfies ModelDefinition[];
