import type { ModelDefinition } from "@/models.js";

export const anthropicModels = [
	{
		id: "claude-3-7-sonnet",
		name: "Claude 3.7 Sonnet",
		description:
			"Intelligent model with extended thinking for complex reasoning tasks.",
		family: "anthropic",
		releasedAt: new Date("2025-02-24"),
		providers: [
			{
				test: "skip",
				providerId: "anthropic",
				modelName: "claude-3-7-sonnet-latest",
				inputPrice: 3.0 / 1e6,
				outputPrice: 15.0 / 1e6,
				cachedInputPrice: 0.3 / 1e6,
				minCacheableTokens: 1024,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 8192,
				reasoning: true,
				reasoningMaxTokens: true,
				streaming: true,
				vision: false,
				tools: true,
				webSearch: true,
				webSearchPrice: 0.01, // $10 per 1000 searches
			},
			{
				test: "skip",
				providerId: "kiwillm-free-ai-hub",
				modelName: "anthropic/claude-3.7-sonnet",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 8192,
				reasoning: true,
				reasoningMaxTokens: true,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "aws-bedrock",
				modelName: "anthropic.claude-3-7-sonnet-20250219-v1:0",
				deprecatedAt: new Date("2025-10-28"),
				deactivatedAt: new Date("2026-04-28"),
				inputPrice: 3.0 / 1e6,
				outputPrice: 15.0 / 1e6,
				cachedInputPrice: 0.3 / 1e6,
				minCacheableTokens: 1024,
				requestPrice: 0,
				discount: 0.3,
				contextSize: 200000,
				maxOutput: 8192,
				reasoning: true,
				reasoningMaxTokens: true,
				reasoningOutput: "omit",
				streaming: true,
				vision: false,
				tools: true,
			},
		],
	},
	{
		id: "claude-3-5-haiku-20241022",
		name: "Claude 3.5 Haiku (2024-10-22)",
		description:
			"Fast, compact model for quick responses and efficient processing.",
		family: "anthropic",
		releasedAt: new Date("2024-10-22"),
		providers: [
			{
				providerId: "anthropic",
				modelName: "claude-3-5-haiku-20241022",
				inputPrice: 0.8 / 1e6,
				outputPrice: 4.0 / 1e6,
				cachedInputPrice: 0.08 / 1e6,
				minCacheableTokens: 2048,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
				webSearch: true,
				webSearchPrice: 0.01, // $10 per 1000 searches
				deprecatedAt: new Date("2025-12-19"),
				deactivatedAt: new Date("2026-02-19T17:00:00Z"),
			},
			{
				test: "skip",
				providerId: "kiwillm-claude-talkai",
				modelName: "claude-3-5-haiku-20241022",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "claude-3-7-sonnet-20250219",
		name: "Claude 3.7 Sonnet (2025-02-19)",
		description:
			"Dated version of Claude 3.7 Sonnet with reasoning capabilities.",
		family: "anthropic",
		releasedAt: new Date("2025-02-19"),
		providers: [
			{
				test: "skip",
				providerId: "anthropic",
				modelName: "claude-3-7-sonnet-20250219",
				inputPrice: 3.0 / 1e6,
				outputPrice: 15.0 / 1e6,
				cachedInputPrice: 0.3 / 1e6,
				minCacheableTokens: 1024,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				reasoning: true,
				reasoningMaxTokens: true,
				tools: true,
				webSearch: true,
				webSearchPrice: 0.01, // $10 per 1000 searches
			},
		],
	},
	{
		id: "claude-3-5-sonnet-20241022",
		name: "Claude 3.5 Sonnet (2024-10-22)",
		description: "Previous generation Sonnet model for balanced performance.",
		family: "anthropic",
		releasedAt: new Date("2024-10-22"),
		providers: [
			{
				test: "skip",
				providerId: "anthropic",
				modelName: "claude-3-5-sonnet-20241022",
				inputPrice: 3.0 / 1e6,
				outputPrice: 15.0 / 1e6,
				cachedInputPrice: 0.3 / 1e6,
				minCacheableTokens: 1024,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
				webSearch: true,
				webSearchPrice: 0.01, // $10 per 1000 searches
				deactivatedAt: new Date("2025-10-22T00:00:00Z"),
			},
			{
				test: "skip",
				providerId: "kiwillm-claude-talkai",
				modelName: "claude-3-5-sonnet-20241022",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
				reasoning: true,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "aws-bedrock",
				modelName: "anthropic.claude-3-5-sonnet-20241022-v2:0",
				deprecatedAt: new Date("2025-10-28"),
				deactivatedAt: new Date("2026-04-28"),
				inputPrice: 3.0 / 1e6,
				outputPrice: 15.0 / 1e6,
				cachedInputPrice: 0.3 / 1e6,
				minCacheableTokens: 1024,
				requestPrice: 0,
				discount: 0.3,
				contextSize: 200000,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
			},
		],
	},
	{
		id: "claude-2.1",
		name: "Claude 2.1",
		description: "Legacy Claude model, deprecated in 2025.",
		family: "anthropic",
		releasedAt: new Date("2023-11-21"),
		providers: [
			{
				providerId: "anthropic",
				modelName: "claude-2.1",
				inputPrice: 8.0 / 1e6,
				outputPrice: 24.0 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				deprecatedAt: new Date("2025-06-15T00:00:00Z"),
				deactivatedAt: new Date("2025-07-21T16:00:00Z"),
			},
		],
	},
	{
		id: "claude-sonnet-4-20250514",
		name: "Claude Sonnet 4 (2025-05-14)",
		description: "Claude Sonnet 4 with enhanced reasoning and tool use.",
		family: "anthropic",
		releasedAt: new Date("2025-05-14"),
		providers: [
			{
				test: "skip",
				providerId: "anthropic",
				modelName: "claude-sonnet-4-20250514",
				inputPrice: 3.0 / 1e6,
				outputPrice: 15.0 / 1e6,
				cachedInputPrice: 0.3 / 1e6,
				minCacheableTokens: 1024,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: undefined,
				reasoning: true,
				reasoningMaxTokens: true,
				streaming: true,
				vision: false,
				tools: true,
				webSearch: true,
				webSearchPrice: 0.01, // $10 per 1000 searches
			},
			{
				test: "skip",
				providerId: "kiwillm-free-ai-hub",
				modelName: "anthropic/claude-sonnet-4",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: undefined,
				reasoning: true,
				reasoningMaxTokens: true,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "aws-bedrock",
				modelName: "anthropic.claude-sonnet-4-20250514-v1:0",
				inputPrice: 3.0 / 1e6,
				outputPrice: 15.0 / 1e6,
				cachedInputPrice: 0.3 / 1e6,
				minCacheableTokens: 1024,
				requestPrice: 0,
				discount: 0.3,
				contextSize: 200000,
				maxOutput: undefined,
				reasoning: true,
				reasoningMaxTokens: true,
				reasoningOutput: "omit",
				streaming: true,
				vision: false,
				tools: true,
			},
		],
	},
	{
		id: "claude-sonnet-4-5",
		name: "Claude Sonnet 4.5",
		description:
			"Latest Claude Sonnet with improved reasoning and extended thinking.",
		family: "anthropic",
		releasedAt: new Date("2025-09-29"),
		providers: [
			{
				test: "skip",
				providerId: "anthropic",
				modelName: "claude-sonnet-4-5",
				inputPrice: 3.0 / 1e6,
				outputPrice: 15.0 / 1e6,
				cachedInputPrice: 0.3 / 1e6,
				minCacheableTokens: 1024,
				requestPrice: 0,
				contextSize: 200000,
				reasoning: true,
				reasoningMaxTokens: true,
				maxOutput: 64000,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutputSchema: true,
				webSearch: true,
				webSearchPrice: 0.01, // $10 per 1000 searches
			},
			{
				test: "skip",
				providerId: "kiwillm-free-ai-hub",
				modelName: "anthropic/claude-sonnet-4.5",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 64000,
				reasoning: true,
				reasoningMaxTokens: true,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
				jsonOutputSchema: true,
			},
			{
				test: "skip",
				providerId: "kiwillm-n33-ai",
				modelName: "claude-sonnet-4.5",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 64000,
				reasoning: true,
				reasoningMaxTokens: true,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
				jsonOutputSchema: true,
			},
			{
				test: "skip",
				providerId: "aws-bedrock",
				modelName: "anthropic.claude-sonnet-4-5-20250929-v1:0",
				inputPrice: 3.0 / 1e6,
				outputPrice: 15.0 / 1e6,
				cachedInputPrice: 0.3 / 1e6,
				minCacheableTokens: 1024,
				requestPrice: 0,
				discount: 0.3,
				contextSize: 200000,
				maxOutput: 8192,
				reasoning: true,
				reasoningMaxTokens: true,
				reasoningOutput: "omit",
				streaming: true,
				vision: false,
				tools: true,
				jsonOutputSchema: true,
			},
		],
	},
	{
		id: "claude-sonnet-4-5-20250929",
		name: "Claude Sonnet 4.5 (2025-09-29)",
		description:
			"Latest Claude Sonnet with improved reasoning and extended thinking.",
		family: "anthropic",
		releasedAt: new Date("2025-09-29"),
		providers: [
			{
				test: "skip",
				providerId: "anthropic",
				modelName: "claude-sonnet-4-5-20250929",
				inputPrice: 3.0 / 1e6,
				outputPrice: 15.0 / 1e6,
				cachedInputPrice: 0.3 / 1e6,
				minCacheableTokens: 1024,
				requestPrice: 0,
				contextSize: 200000,
				reasoning: true,
				reasoningMaxTokens: true,
				maxOutput: 64000,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutputSchema: true,
				webSearch: true,
				webSearchPrice: 0.01, // $10 per 1000 searches
			},
			{
				test: "skip",
				providerId: "aws-bedrock",
				modelName: "anthropic.claude-sonnet-4-5-20250929-v1:0",
				inputPrice: 3.0 / 1e6,
				outputPrice: 15.0 / 1e6,
				cachedInputPrice: 0.3 / 1e6,
				minCacheableTokens: 1024,
				requestPrice: 0,
				discount: 0.3,
				contextSize: 200000,
				maxOutput: 8192,
				reasoning: true,
				reasoningMaxTokens: true,
				reasoningOutput: "omit",
				streaming: true,
				vision: false,
				tools: true,
				jsonOutputSchema: true,
			},
		],
	},
	{
		id: "claude-sonnet-4-6",
		name: "Claude Sonnet 4.6",
		description:
			"Claude Sonnet 4.6 with advanced reasoning and extended thinking capabilities.",
		family: "anthropic",
		releasedAt: new Date("2026-02-17"),
		providers: [
			{
				providerId: "anthropic",
				modelName: "claude-sonnet-4-6",
				inputPrice: 3.0 / 1e6,
				outputPrice: 15.0 / 1e6,
				cachedInputPrice: 0.3 / 1e6,
				minCacheableTokens: 2048,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 64000,
				reasoning: true,
				reasoningMaxTokens: true,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutputSchema: true,
				webSearch: true,
				webSearchPrice: 0.01, // $10 per 1000 searches
			},
			{
				providerId: "aws-bedrock",
				modelName: "anthropic.claude-sonnet-4-6",
				inputPrice: 3.0 / 1e6,
				outputPrice: 15.0 / 1e6,
				cachedInputPrice: 0.3 / 1e6,
				minCacheableTokens: 2048,
				requestPrice: 0,
				discount: 0.3,
				contextSize: 200000,
				maxOutput: 64000,
				reasoning: true,
				reasoningMaxTokens: true,
				reasoningOutput: "omit",
				streaming: true,
				vision: false,
				tools: true,
				jsonOutputSchema: true,
			},
			{
				test: "skip",
				providerId: "google-vertex",
				modelName: "claude-sonnet-4-6",
				inputPrice: 3.0 / 1e6,
				outputPrice: 15.0 / 1e6,
				cachedInputPrice: 0.3 / 1e6,
				minCacheableTokens: 2048,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 64000,
				reasoning: true,
				reasoningMaxTokens: true,
				streaming: true,
				vision: false,
				tools: true,
			},
		],
	},
	{
		id: "claude-haiku-4-5",
		name: "Claude Haiku 4.5",
		description:
			"Fast, efficient model for high-volume, low-latency applications.",
		family: "anthropic",
		releasedAt: new Date("2025-10-15"),
		providers: [
			{
				providerId: "anthropic",
				modelName: "claude-haiku-4-5",
				inputPrice: 1.0 / 1e6,
				outputPrice: 5.0 / 1e6,
				cachedInputPrice: 0.1 / 1e6,
				minCacheableTokens: 4096,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 64000,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutputSchema: true,
				webSearch: true,
				webSearchPrice: 0.01, // $10 per 1000 searches
			},
			{
				test: "skip",
				providerId: "kiwillm-free-ai-hub",
				modelName: "anthropic/claude-haiku-4.5",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 64000,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
				jsonOutputSchema: true,
			},
			{
				test: "skip",
				providerId: "kiwillm-n33-ai",
				modelName: "claude-haiku-4.5",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 64000,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
				jsonOutputSchema: true,
			},
			{
				providerId: "aws-bedrock",
				modelName: "anthropic.claude-haiku-4-5-20251001-v1:0",
				inputPrice: 1.0 / 1e6,
				outputPrice: 5.0 / 1e6,
				cachedInputPrice: 0.1 / 1e6,
				minCacheableTokens: 4096,
				requestPrice: 0,
				discount: 0.3,
				contextSize: 200000,
				maxOutput: 64000,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutputSchema: true,
			},
		],
	},
	{
		id: "claude-haiku-4-5-20251001",
		name: "Claude Haiku 4.5 (2025-10-01)",
		description:
			"Fast, efficient model for high-volume, low-latency applications.",
		family: "anthropic",
		releasedAt: new Date("2025-10-15"),
		providers: [
			{
				providerId: "anthropic",
				modelName: "claude-haiku-4-5-20251001",
				inputPrice: 1.0 / 1e6,
				outputPrice: 5.0 / 1e6,
				cachedInputPrice: 0.1 / 1e6,
				minCacheableTokens: 4096,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 64000,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutputSchema: true,
				webSearch: true,
				webSearchPrice: 0.01, // $10 per 1000 searches
			},
			{
				providerId: "aws-bedrock",
				modelName: "anthropic.claude-haiku-4-5-20251001-v1:0",
				inputPrice: 1.0 / 1e6,
				outputPrice: 5.0 / 1e6,
				cachedInputPrice: 0.1 / 1e6,
				minCacheableTokens: 4096,
				requestPrice: 0,
				discount: 0.3,
				contextSize: 200000,
				maxOutput: 64000,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutputSchema: true,
			},
		],
	},
	{
		id: "claude-opus-4-20250514",
		name: "Claude Opus 4 (2025-05-14)",
		description:
			"High-capability model for complex analysis and nuanced tasks.",
		family: "anthropic",
		releasedAt: new Date("2025-05-22"),
		providers: [
			{
				test: "skip",
				providerId: "anthropic",
				modelName: "claude-opus-4-20250514",
				inputPrice: 15.0 / 1e6,
				outputPrice: 75.0 / 1e6,
				cachedInputPrice: 1.5 / 1e6,
				minCacheableTokens: 1024,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: undefined,
				reasoning: true,
				reasoningMaxTokens: true,
				streaming: true,
				vision: false,
				tools: true,
				webSearch: true,
				webSearchPrice: 0.01, // $10 per 1000 searches
			},
			{
				test: "skip",
				providerId: "kiwillm-free-ai-hub",
				modelName: "anthropic/claude-opus-4",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: undefined,
				reasoning: true,
				reasoningMaxTokens: true,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "aws-bedrock",
				modelName: "anthropic.claude-opus-4-20250514-v1:0",
				inputPrice: 15.0 / 1e6,
				outputPrice: 75.0 / 1e6,
				cachedInputPrice: 1.5 / 1e6,
				minCacheableTokens: 1024,
				requestPrice: 0,
				discount: 0.3,
				contextSize: 200000,
				maxOutput: undefined,
				reasoning: true,
				reasoningMaxTokens: true,
				reasoningOutput: "omit",
				streaming: true,
				vision: false,
				tools: true,
			},
		],
	},
	{
		id: "claude-opus-4-1-20250805",
		name: "Claude Opus 4.1",
		description: "Updated Opus with vision support and 32K output.",
		family: "anthropic",
		releasedAt: new Date("2025-08-05"),
		providers: [
			{
				test: "skip",
				providerId: "anthropic",
				modelName: "claude-opus-4-1-20250805",
				inputPrice: 15.0 / 1e6,
				outputPrice: 75.0 / 1e6,
				cachedInputPrice: 1.5 / 1e6,
				minCacheableTokens: 1024,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 32000,
				streaming: true,
				vision: true,
				reasoning: true,
				reasoningMaxTokens: true,
				tools: true,
				jsonOutputSchema: true,
				webSearch: true,
				webSearchPrice: 0.01, // $10 per 1000 searches
			},
			{
				test: "skip",
				providerId: "kiwillm-free-ai-hub",
				modelName: "anthropic/claude-opus-4.1",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 32000,
				streaming: true,
				vision: true,
				reasoning: true,
				reasoningMaxTokens: true,
				tools: true,
				jsonOutput: true,
				jsonOutputSchema: true,
			},
			{
				test: "skip",
				providerId: "aws-bedrock",
				modelName: "anthropic.claude-opus-4-1-20250805-v1:0",
				inputPrice: 15.0 / 1e6,
				outputPrice: 75.0 / 1e6,
				cachedInputPrice: 1.5 / 1e6,
				minCacheableTokens: 1024,
				requestPrice: 0,
				discount: 0.3,
				contextSize: 200000,
				maxOutput: 32000,
				streaming: true,
				vision: true,
				reasoning: true,
				reasoningMaxTokens: true,
				reasoningOutput: "omit",
				tools: true,
				jsonOutputSchema: true,
			},
		],
	},
	{
		id: "claude-3-5-sonnet-20240620",
		name: "Claude 3.5 Sonnet (Old)",
		description: "Original Claude 3.5 Sonnet with vision capabilities.",
		family: "anthropic",
		releasedAt: new Date("2024-06-20"),
		providers: [
			{
				test: "skip",
				providerId: "anthropic",
				modelName: "claude-3-5-sonnet-20240620",
				deactivatedAt: new Date("2026-02-19"),
				inputPrice: 3.0 / 1e6,
				outputPrice: 15.0 / 1e6,
				cachedInputPrice: 0.3 / 1e6,
				minCacheableTokens: 1024,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 8192,
				streaming: true,
				vision: true,
				tools: true,
			},
		],
	},
	{
		id: "claude-3-5-sonnet",
		name: "Claude 3.5 Sonnet",
		description:
			"Latest Claude 3.5 Sonnet with balanced speed and intelligence.",
		family: "anthropic",
		releasedAt: new Date("2024-06-20"),
		providers: [
			{
				test: "skip",
				providerId: "anthropic",
				modelName: "claude-3-5-sonnet-latest",
				inputPrice: 3.0 / 1e6,
				outputPrice: 15.0 / 1e6,
				cachedInputPrice: 0.3 / 1e6,
				minCacheableTokens: 1024,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: true,
				webSearch: true,
				webSearchPrice: 0.01, // $10 per 1000 searches
			},
			{
				test: "skip",
				providerId: "kiwillm-free-ai-hub",
				modelName: "anthropic/claude-3.5-sonnet",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "claude-3-5-haiku",
		name: "Claude 3.5 Haiku",
		description: "Fastest Claude model for instant responses at scale.",
		family: "anthropic",
		releasedAt: new Date("2024-10-22"),
		providers: [
			{
				providerId: "anthropic",
				modelName: "claude-3-5-haiku-latest",
				inputPrice: 0.8 / 1e6,
				outputPrice: 4.0 / 1e6,
				cachedInputPrice: 0.08 / 1e6,
				minCacheableTokens: 2048,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
				webSearch: true,
				webSearchPrice: 0.01, // $10 per 1000 searches
				deprecatedAt: new Date("2025-12-19"),
				deactivatedAt: new Date("2026-02-19T17:00:00Z"),
			},
			{
				test: "skip",
				providerId: "kiwillm-free-ai-hub",
				modelName: "anthropic/claude-3.5-haiku",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
			{
				providerId: "aws-bedrock",
				modelName: "anthropic.claude-3-5-haiku-20241022-v1:0",
				deprecatedAt: new Date("2025-10-28"),
				deactivatedAt: new Date("2026-04-28"),
				inputPrice: 0.8 / 1e6,
				outputPrice: 4.0 / 1e6,
				cachedInputPrice: 0.08 / 1e6,
				minCacheableTokens: 2048,
				requestPrice: 0,
				discount: 0.3,
				contextSize: 200000,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
			},
		],
	},
	{
		id: "claude-3-opus",
		name: "Claude 3 Opus",
		description: "Most capable Claude 3 model for expert-level tasks.",
		family: "anthropic",
		releasedAt: new Date("2024-03-04"),
		providers: [
			{
				test: "skip",
				providerId: "anthropic",
				modelName: "claude-3-opus-20240229",
				inputPrice: 15.0 / 1e6,
				outputPrice: 75.0 / 1e6,
				cachedInputPrice: 1.5 / 1e6,
				minCacheableTokens: 1024,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 4096,
				streaming: true,
				vision: true,
				tools: true,
			},
			{
				test: "skip",
				providerId: "kiwillm-claude-talkai",
				modelName: "claude-3-opus-20240229",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 4096,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "claude-3-haiku",
		name: "Claude 3 Haiku",
		description:
			"Compact Claude 3 model with vision for fast, affordable inference.",
		family: "anthropic",
		releasedAt: new Date("2024-03-04"),
		providers: [
			{
				providerId: "anthropic",
				modelName: "claude-3-haiku-20240307",
				inputPrice: 0.25 / 1e6,
				outputPrice: 1.25 / 1e6,
				cachedInputPrice: 0.03 / 1e6,
				minCacheableTokens: 1024,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 4096,
				streaming: true,
				vision: true,
				tools: true,
			},
			{
				test: "skip",
				providerId: "kiwillm-free-ai-hub",
				modelName: "anthropic/claude-3-haiku",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 4096,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "claude-3-haiku-20240307",
		name: "Claude 3 Haiku (2024-03-07)",
		description:
			"Compact Claude 3 model with vision for fast, affordable inference.",
		family: "anthropic",
		releasedAt: new Date("2024-03-04"),
		providers: [
			{
				providerId: "anthropic",
				modelName: "claude-3-haiku-20240307",
				inputPrice: 0.25 / 1e6,
				outputPrice: 1.25 / 1e6,
				cachedInputPrice: 0.03 / 1e6,
				minCacheableTokens: 1024,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 4096,
				streaming: true,
				vision: true,
				tools: true,
			},
			{
				test: "skip",
				providerId: "kiwillm-claude-talkai",
				modelName: "claude-3-haiku-20240307",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 4096,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "claude-3-5-sonnet-reasoning",
		name: "Claude 3.5 Sonnet Reasoning",
		description:
			"Reasoning-tuned Claude 3.5 Sonnet variant exposed through the Claude TalkAI worker.",
		family: "anthropic",
		providers: [
			{
				test: "skip",
				providerId: "kiwillm-claude-talkai",
				modelName: "claude-3-5-sonnet-reasoning",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 8192,
				reasoning: true,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "claude-3-sonnet-20240229",
		name: "Claude 3 Sonnet (2024-02-29)",
		description:
			"Claude 3 Sonnet snapshot exposed through the Claude TalkAI worker.",
		family: "anthropic",
		releasedAt: new Date("2024-02-29"),
		providers: [
			{
				test: "skip",
				providerId: "kiwillm-claude-talkai",
				modelName: "claude-3-sonnet-20240229",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 4096,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "claude-2",
		name: "Claude 2",
		description:
			"Legacy Claude 2 model exposed through the Claude TalkAI worker.",
		family: "anthropic",
		providers: [
			{
				test: "skip",
				providerId: "kiwillm-claude-talkai",
				modelName: "claude-2",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 100000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "claude-instant",
		name: "Claude Instant",
		description:
			"Fast legacy Claude Instant model exposed through the Claude TalkAI worker.",
		family: "anthropic",
		providers: [
			{
				test: "skip",
				providerId: "kiwillm-claude-talkai",
				modelName: "claude-instant",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 100000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "claude-opus-4-5-20251101",
		name: "Claude Opus 4.5",
		description:
			"Claude Opus 4.5 is Anthropic's advanced reasoning model built for complex coding, agentic workflows, and long-running tasks with improved multimodal performance, efficiency, and reliability.",
		family: "anthropic",
		releasedAt: new Date("2025-11-24"),
		providers: [
			{
				providerId: "anthropic",
				modelName: "claude-opus-4-5-20251101",
				inputPrice: 5.0 / 1e6,
				outputPrice: 25.0 / 1e6,
				cachedInputPrice: 0.5 / 1e6,
				minCacheableTokens: 4096,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 32000,
				reasoning: true,
				reasoningMaxTokens: true,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutputSchema: true,
				supportedParameters: ["temperature", "max_tokens", "top_p", "effort"],
				webSearch: true,
				webSearchPrice: 0.01, // $10 per 1000 searches
			},
			{
				test: "skip",
				providerId: "kiwillm-free-ai-hub",
				modelName: "anthropic/claude-opus-4.5",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 32000,
				reasoning: true,
				reasoningMaxTokens: true,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
				jsonOutputSchema: true,
			},
			{
				test: "skip",
				providerId: "aws-bedrock",
				modelName: "anthropic.claude-opus-4-5-20251101-v1:0",
				inputPrice: 5.0 / 1e6,
				outputPrice: 25.0 / 1e6,
				cachedInputPrice: 0.5 / 1e6,
				minCacheableTokens: 4096,
				requestPrice: 0,
				discount: 0.3,
				contextSize: 200000,
				maxOutput: 32000,
				reasoning: true,
				reasoningMaxTokens: true,
				reasoningOutput: "omit",
				streaming: true,
				vision: true,
				tools: true,
				jsonOutputSchema: true,
			},
			{
				test: "skip",
				providerId: "google-vertex",
				modelName: "claude-opus-4-5@20251101",
				inputPrice: 5.0 / 1e6,
				outputPrice: 25.0 / 1e6,
				cachedInputPrice: 0.5 / 1e6,
				minCacheableTokens: 4096,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 32000,
				reasoning: true,
				reasoningMaxTokens: true,
				streaming: true,
				vision: true,
				tools: true,
			},
		],
	},
	{
		id: "claude-opus-4-6",
		name: "Claude Opus 4.6",
		description:
			"Claude Opus 4.6 is Anthropic's latest flagship model with advanced reasoning capabilities for complex coding, agentic workflows, and long-running tasks.",
		family: "anthropic",
		releasedAt: new Date("2026-02-05"),
		providers: [
			{
				providerId: "anthropic",
				modelName: "claude-opus-4-6",
				inputPrice: 5.0 / 1e6,
				outputPrice: 25.0 / 1e6,
				cachedInputPrice: 0.5 / 1e6,
				minCacheableTokens: 4096,
				pricingTiers: [
					{
						name: "Up to 200K",
						upToTokens: 200000,
						inputPrice: 5.0 / 1e6,
						outputPrice: 25.0 / 1e6,
						cachedInputPrice: 0.5 / 1e6,
					},
					{
						name: "Over 200K",
						upToTokens: Infinity,
						inputPrice: 10.0 / 1e6,
						outputPrice: 37.5 / 1e6,
						cachedInputPrice: 1.0 / 1e6,
					},
				],
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: 128000,
				reasoning: true,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutputSchema: true,
				supportedParameters: ["temperature", "max_tokens", "top_p", "effort"],
				webSearch: true,
				webSearchPrice: 0.01, // $10 per 1000 searches
			},
			{
				test: "skip",
				providerId: "kiwillm-free-ai-hub",
				modelName: "anthropic/claude-opus-4.6",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: 128000,
				reasoning: true,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
				jsonOutputSchema: true,
			},
			{
				test: "skip",
				providerId: "aws-bedrock",
				modelName: "anthropic.claude-opus-4-6-v1",
				inputPrice: 5.0 / 1e6,
				outputPrice: 25.0 / 1e6,
				cachedInputPrice: 0.5 / 1e6,
				minCacheableTokens: 4096,
				requestPrice: 0,
				discount: 0.3,
				contextSize: 1000000,
				maxOutput: 128000,
				reasoning: true,
				reasoningOutput: "omit",
				streaming: true,
				vision: true,
				tools: true,
				jsonOutputSchema: true,
			},
		],
	},
] as const satisfies ModelDefinition[];
