import type { ModelDefinition } from "@/models.js";

export const deepseekModels = [
	{
		id: "deepseek-chat-v3-0324",
		name: "DeepSeek Chat V3 0324",
		description:
			"DeepSeek chat snapshot exposed through the KiwiLLM free AI hub worker.",
		family: "deepseek",
		providers: [
			{
				test: "skip",
				providerId: "kiwillm-free-ai-hub",
				modelName: "deepseek/deepseek-chat-v3-0324",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "deepseek-chat",
		name: "DeepSeek Chat",
		description: "DeepSeek's chat-optimized model for general tasks.",
		family: "deepseek",
		providers: [
			{
				test: "skip",
				providerId: "kiwillm-deepseek",
				modelName: "deepseek-chat",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "kiwillm-claude-talkai",
				modelName: "deepseek-reasoner",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: undefined,
				reasoning: true,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "deepseek-reasoner",
		name: "DeepSeek Reasoner",
		description: "DeepSeek reasoning model tuned for step-by-step analysis.",
		family: "deepseek",
		providers: [
			{
				test: "skip",
				providerId: "kiwillm-deepseek",
				modelName: "deepseek-reasoner",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: undefined,
				reasoning: true,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "kiwillm-claude-talkai",
				modelName: "deepseek-r1",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: undefined,
				reasoning: true,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "deepseek-v3.2-exp",
		name: "DeepSeek V3.2 Experimental",
		description: "Experimental DeepSeek V3.2 worker-backed variant.",
		family: "deepseek",
		stability: "experimental" as const,
		providers: [
			{
				test: "skip",
				providerId: "kiwillm-deepseek",
				modelName: "deepseek-v3.2-exp",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
				stability: "experimental" as const,
			},
		],
	},
	{
		id: "deepseek-v3",
		name: "DeepSeek V3",
		description:
			"Large-scale Chinese AI model with strong multilingual capabilities.",
		family: "deepseek",
		releasedAt: new Date("2024-12-26"),
		providers: [
			{
				test: "skip",
				providerId: "kiwillm-deepseek",
				modelName: "deepseek-v3",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
			},
			{
				providerId: "nebius",
				stability: "unstable" as const,
				modelName: "deepseek-ai/DeepSeek-V3",
				inputPrice: 0.5 / 1e6,
				outputPrice: 1.5 / 1e6,
				requestPrice: 0,
				contextSize: 64000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: false,
				deactivatedAt: new Date("2025-11-03"),
			},
		],
	},
	{
		id: "deepseek-vl",
		name: "DeepSeek VL",
		description:
			"DeepSeek vision-language model exposed via the KiwiLLM worker.",
		family: "deepseek",
		providers: [
			{
				test: "skip",
				providerId: "kiwillm-deepseek",
				modelName: "deepseek-vl",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: undefined,
				streaming: true,
				vision: true,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "deepseek-v2",
		name: "DeepSeek V2",
		description: "DeepSeek V2 general-purpose model.",
		family: "deepseek",
		providers: [
			{
				test: "skip",
				providerId: "kiwillm-deepseek",
				modelName: "deepseek-v2",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "deepseek-v2.5",
		name: "DeepSeek V2.5",
		description: "DeepSeek V2.5 worker-backed variant.",
		family: "deepseek",
		providers: [
			{
				test: "skip",
				providerId: "kiwillm-deepseek",
				modelName: "deepseek-v2.5",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "deepseek-math",
		name: "DeepSeek Math",
		description: "DeepSeek model specialized for mathematical reasoning.",
		family: "deepseek",
		providers: [
			{
				test: "skip",
				providerId: "kiwillm-deepseek",
				modelName: "deepseek-math",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "deepseek-coder",
		name: "DeepSeek Coder",
		description: "DeepSeek model optimized for coding and code generation.",
		family: "deepseek",
		providers: [
			{
				test: "skip",
				providerId: "kiwillm-deepseek",
				modelName: "deepseek-coder",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "deepseek-instruct",
		name: "DeepSeek Instruct",
		description: "Instruction-following DeepSeek model exposed via the worker.",
		family: "deepseek",
		providers: [
			{
				test: "skip",
				providerId: "kiwillm-deepseek",
				modelName: "deepseek-instruct",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "deepseek-r1",
		name: "DeepSeek R1",
		description: "DeepSeek reasoning model exposed through the KiwiLLM worker.",
		family: "deepseek",
		providers: [
			{
				test: "skip",
				providerId: "kiwillm-deepseek",
				modelName: "deepseek-r1",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: undefined,
				reasoning: true,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "deepseek-r1-0528",
		name: "DeepSeek R1 (0528)",
		description: "May 2028 version of DeepSeek R1 reasoning model.",
		family: "deepseek",
		releasedAt: new Date("2025-05-28"),
		providers: [
			{
				providerId: "nebius",
				modelName: "deepseek-ai/DeepSeek-R1-0528",
				inputPrice: 0.8 / 1e6,
				outputPrice: 2.4 / 1e6,
				requestPrice: 0,
				contextSize: 64000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				stability: "unstable" as const,
				jsonOutput: false,
			},
		],
	},
	{
		id: "deepseek-r1-distill-llama-70b",
		name: "DeepSeek R1 Distill Llama 70B",
		description: "DeepSeek R1 distilled into Llama 70B architecture.",
		family: "deepseek",
		stability: "beta" as const,
		releasedAt: new Date("2025-01-20"),
		providers: [
			{
				providerId: "groq",
				modelName: "deepseek-r1-distill-llama-70b",
				inputPrice: 0.75 / 1e6,
				outputPrice: 0.99 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
				deactivatedAt: new Date("2025-10-09"),
			},
		],
	},
	{
		id: "deepseek-v3.1",
		name: "DeepSeek V3.1",
		description:
			"Updated DeepSeek V3 with vision, tools, and improved performance.",
		family: "deepseek",
		releasedAt: new Date("2025-08-21"),
		providers: [
			{
				providerId: "canopywave",
				modelName: "deepseek/deepseek-chat-v3.1",
				deactivatedAt: new Date("2025-12-15"),
				inputPrice: 0.27 / 1e6,
				outputPrice: 1.0 / 1e6,
				cachedInputPrice: 0.07 / 1e6,
				discount: 0.3,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutputSchema: false,
				jsonOutput: true,
			},
			{
				providerId: "bytedance",
				modelName: "deepseek-v3-1-250821",
				inputPrice: 0.56 / 1e6,
				cachedInputPrice: 0.112 / 1e6,
				outputPrice: 1.68 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: 32768,
				reasoning: true,
				reasoningOutput: "omit" as const,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: false,
			},
		],
	},
	{
		id: "deepseek-v3.2",
		name: "DeepSeek V3.2",
		description:
			"Latest DeepSeek V3 with vision, tools, and improved performance.",
		family: "deepseek",
		releasedAt: new Date("2025-09-29"),
		providers: [
			{
				test: "skip",
				providerId: "kiwillm-deepseek",
				modelName: "deepseek-v3.2",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 163840,
				maxOutput: undefined,
				streaming: true,
				vision: true,
				tools: false,
				jsonOutput: true,
			},
			{
				providerId: "deepseek",
				modelName: "deepseek-chat",
				inputPrice: 0.28 / 1e6,
				outputPrice: 0.42 / 1e6,
				cachedInputPrice: 0.028 / 1e6,
				requestPrice: 0,
				contextSize: 163840,
				maxOutput: undefined,
				jsonOutput: true,
				streaming: true,
				vision: true,
				tools: true,
			},
			{
				providerId: "canopywave",
				modelName: "deepseek/deepseek-chat-v3.2",
				inputPrice: 0.26 / 1e6,
				outputPrice: 0.4 / 1e6,
				cachedInputPrice: 0.052 / 1e6,
				discount: 0.3,
				requestPrice: 0,
				contextSize: 163800,
				maxOutput: undefined,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutputSchema: false,
				jsonOutput: true,
			},
			{
				providerId: "bytedance",
				modelName: "deepseek-v3-2-251201",
				inputPrice: 0.28 / 1e6,
				cachedInputPrice: 0.056 / 1e6,
				outputPrice: 0.42 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				reasoning: true,
				reasoningOutput: "omit" as const,
				maxOutput: 131072,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: false,
			},
		],
	},
	{
		id: "deepseek-llm",
		name: "DeepSeek LLM",
		description:
			"Base DeepSeek language model exposed through the KiwiLLM worker.",
		family: "deepseek",
		providers: [
			{
				test: "skip",
				providerId: "kiwillm-deepseek",
				modelName: "deepseek-llm",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "deepseek-moe",
		name: "DeepSeek MoE",
		description: "DeepSeek mixture-of-experts worker-backed model.",
		family: "deepseek",
		providers: [
			{
				test: "skip",
				providerId: "kiwillm-deepseek",
				modelName: "deepseek-moe",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "deepseek-67b",
		name: "DeepSeek 67B",
		description: "DeepSeek 67B worker-backed model.",
		family: "deepseek",
		providers: [
			{
				test: "skip",
				providerId: "kiwillm-deepseek",
				modelName: "deepseek-67b",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "deepseek-33b",
		name: "DeepSeek 33B",
		description: "DeepSeek 33B worker-backed model.",
		family: "deepseek",
		providers: [
			{
				test: "skip",
				providerId: "kiwillm-deepseek",
				modelName: "deepseek-33b",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
			},
		],
	},
] as const satisfies ModelDefinition[];
