import type { ModelDefinition } from "@/models.js";

export const metaModels = [
	{
		id: "llama-3.1-8b-instruct",
		name: "Llama 3.1 8B Instruct",
		description: "Compact Llama 3.1 for efficient text generation.",
		family: "meta",
		releasedAt: new Date("2024-07-23"),
		providers: [
			{
				providerId: "aws-bedrock",
				modelName: "meta.llama3-1-8b-instruct-v1:0",
				stability: "unstable",
				inputPrice: 0.22 / 1e6,
				outputPrice: 0.22 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: 2048,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: false,
			},
			{
				providerId: "nebius",
				modelName: "meta-llama/Meta-Llama-3.1-8B-Instruct",
				inputPrice: 0.02 / 1e6,
				outputPrice: 0.06 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: false,
			},
			{
				providerId: "inference.net",
				stability: "unstable",
				modelName: "meta-llama/llama-3.1-8b-instruct/fp-8",
				inputPrice: 0.07 / 1e6,
				outputPrice: 0.33 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: false,
			},
			{
				providerId: "together.ai",
				modelName: "meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo",
				inputPrice: 0.06 / 1e6,
				outputPrice: 0.06 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: false,
			},
			{
				// Cerebras: FP16
				providerId: "cerebras",
				modelName: "llama3.1-8b",
				inputPrice: 0.1 / 1e6,
				outputPrice: 0.1 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				// Note: Tool calling is unreliable for llama3.1-8b on Cerebras
				tools: false,
				jsonOutput: true,
				supportedParameters: [
					"temperature",
					"max_tokens",
					"top_p",
					"response_format",
				],
			},
			{
				test: "skip",
				providerId: "kiwillm-cerebras-ai",
				modelName: "llama3.1-8b",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
			},
			{
				providerId: "novita",
				modelName: "meta-llama/llama-3.1-8b-instruct",
				inputPrice: 0.02 / 1e6,
				outputPrice: 0.05 / 1e6,
				requestPrice: 0,
				contextSize: 16384,
				maxOutput: 16384,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "llama-3.1-70b-instruct",
		name: "Llama 3.1 70B Instruct",
		description: "Mid-size Llama 3.1 with balanced performance.",
		family: "meta",
		releasedAt: new Date("2024-07-23"),
		providers: [
			{
				providerId: "aws-bedrock",
				modelName: "meta.llama3-1-70b-instruct-v1:0",
				stability: "unstable",
				inputPrice: 0.72 / 1e6,
				outputPrice: 0.72 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: 2048,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: false,
			},
		],
	},
	{
		id: "llama-3.2-11b-instruct",
		name: "Llama 3.2 11B Instruct",
		description: "Llama 3.2 with improved instruction following.",
		family: "meta",
		releasedAt: new Date("2024-09-25"),
		providers: [
			{
				providerId: "inference.net",
				stability: "unstable",
				modelName: "meta-llama/llama-3.2-11b-instruct/fp-16",
				inputPrice: 0.07 / 1e6,
				outputPrice: 0.33 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "llama-3.1-nemotron-ultra-253b",
		name: "Llama 3.1 Nemotron Ultra 253B",
		description: "NVIDIA-tuned Llama 3.1 253B for maximum capability.",
		family: "meta",
		releasedAt: new Date("2025-04-07"),
		providers: [
			{
				providerId: "nebius",
				modelName: "nvidia/Llama-3_1-Nemotron-Ultra-253B-v1",
				inputPrice: 0.6 / 1e6,
				outputPrice: 1.8 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "llama-guard-4-12b",
		name: "Llama Guard 4 12B",
		description: "Safety-focused model for content moderation.",
		family: "meta",
		releasedAt: new Date("2025-04-30"),
		providers: [
			{
				providerId: "groq",
				modelName: "meta-llama/llama-guard-4-12b",
				inputPrice: 0.2 / 1e6,
				outputPrice: 0.2 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: false,
			},
		],
	},
	{
		id: "llama-3.3-70b-instruct",
		name: "Llama 3.3 70B Instruct",
		description: "Latest Llama 3.3 70B with enhanced capabilities.",
		family: "meta",
		releasedAt: new Date("2024-12-06"),
		providers: [
			{
				providerId: "nebius",
				modelName: "meta-llama/Llama-3.3-70B-Instruct",
				inputPrice: 0.13 / 1e6,
				outputPrice: 0.4 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
			{
				// Cerebras: FP16
				providerId: "cerebras",
				test: "skip",
				modelName: "llama-3.3-70b",
				inputPrice: 0.85 / 1e6,
				outputPrice: 1.2 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
				supportedParameters: [
					"temperature",
					"max_tokens",
					"top_p",
					"response_format",
				],
			},
			{
				providerId: "novita",
				test: "skip",
				modelName: "meta-llama/llama-3.3-70b-instruct",
				inputPrice: 0.135 / 1e6,
				outputPrice: 0.4 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 120000,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: false,
			},
		],
	},
	{
		id: "llama-3.1-405b-instruct",
		name: "Llama 3.1 405B Instruct",
		description: "Largest Llama 3.1 model with 405B parameters.",
		family: "meta",
		releasedAt: new Date("2024-07-23"),
		providers: [
			{
				providerId: "nebius",
				modelName: "meta-llama/Meta-Llama-3.1-405B-Instruct",
				inputPrice: 1.0 / 1e6,
				outputPrice: 3.0 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
				deactivatedAt: new Date("2025-11-03"),
			},
		],
	},
	// {
	// 	id: "llama-guard-3-8b",
	// 	name: "Llama Guard 3 8B",
	// 	family: "meta",
	// 	deprecatedAt: undefined,
	// 	deactivatedAt: undefined,
	// 	providers: [
	// 		{
	// 			providerId: "nebius",
	// 			test: "only",
	// 			modelName: "meta-llama/Llama-Guard-3-8B",
	// 			inputPrice: 0.02 / 1e6,
	// 			outputPrice: 0.06 / 1e6,
	// 			requestPrice: 0,
	// 			contextSize: 8192,
	// 			maxOutput: undefined,
	// 			streaming: true,
	// 			vision: false,
	// 			tools: false,
	// 		},
	// 	],
	// 	jsonOutput: false,
	// },
	{
		id: "llama-4-scout",
		name: "Llama 4 Scout",
		description: "Llama 4 Scout for efficient multi-turn conversations.",
		family: "meta",
		releasedAt: new Date("2025-04-05"),
		providers: [
			{
				providerId: "together.ai",
				stability: "unstable" as const,
				modelName: "meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo",
				inputPrice: 0.18 / 1e6,
				outputPrice: 0.59 / 1e6,
				requestPrice: 0,
				contextSize: 32768,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: false,
			},
		],
	},
	{
		id: "llama-4-scout-17b-instruct",
		name: "Llama 4 Scout 17B Instruct",
		description: "Compact Llama 4 Scout with vision support.",
		family: "meta",
		releasedAt: new Date("2025-04-05"),
		providers: [
			{
				stability: "unstable",
				providerId: "aws-bedrock",
				modelName: "meta.llama4-scout-17b-instruct-v1:0",
				inputPrice: 0.17 / 1e6,
				outputPrice: 0.66 / 1e6,
				requestPrice: 0,
				contextSize: 8192,
				maxOutput: 2048,
				streaming: true,
				reasoningOutput: "omit",
				vision: true,
				tools: false,
				jsonOutput: false,
			},
			{
				providerId: "novita",
				modelName: "meta-llama/llama-4-scout-17b-16e-instruct",
				inputPrice: 0.18 / 1e6,
				outputPrice: 0.59 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 131072,
				streaming: true,
				vision: true,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "llama-4-maverick-17b-instruct",
		name: "Llama 4 Maverick 17B Instruct",
		description: "Llama 4 Maverick variant with vision capabilities.",
		family: "meta",
		releasedAt: new Date("2025-04-05"),
		providers: [
			{
				stability: "unstable",
				providerId: "aws-bedrock",
				modelName: "meta.llama4-maverick-17b-instruct-v1:0",
				inputPrice: 0.24 / 1e6,
				outputPrice: 0.97 / 1e6,
				requestPrice: 0,
				contextSize: 8192,
				maxOutput: 2048,
				streaming: true,
				reasoningOutput: "omit",
				vision: true,
				tools: false,
				jsonOutput: false,
			},
			{
				providerId: "novita",
				modelName: "meta-llama/llama-4-maverick-17b-128e-instruct-fp8",
				inputPrice: 0.27 / 1e6,
				outputPrice: 0.85 / 1e6,
				requestPrice: 0,
				contextSize: 1048576,
				maxOutput: 8192,
				streaming: true,
				vision: true,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "llama-3-8b-instruct",
		name: "Llama 3 8B Instruct",
		description: "Llama 3 8B instruction-following model.",
		family: "meta",
		releasedAt: new Date("2025-04-03"),
		providers: [
			{
				providerId: "novita",
				modelName: "meta-llama/llama-3-8b-instruct",
				inputPrice: 0.04 / 1e6,
				outputPrice: 0.04 / 1e6,
				requestPrice: 0,
				contextSize: 8192,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "llama-3-70b-instruct",
		name: "Llama 3 70B Instruct",
		description: "Llama 3 70B instruction-following model.",
		family: "meta",
		releasedAt: new Date("2024-04-18"),
		providers: [
			{
				providerId: "novita",
				modelName: "meta-llama/llama-3-70b-instruct",
				inputPrice: 0.51 / 1e6,
				outputPrice: 0.74 / 1e6,
				requestPrice: 0,
				contextSize: 8192,
				maxOutput: 8000,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "llama-3.2-3b-instruct",
		name: "Llama 3.2 3B Instruct",
		description: "Compact Llama 3.2 3B for efficient inference.",
		family: "meta",
		releasedAt: new Date("2024-09-18"),
		providers: [
			{
				providerId: "novita",
				stability: "unstable",
				modelName: "meta-llama/llama-3.2-3b-instruct",
				inputPrice: 0.03 / 1e6,
				outputPrice: 0.05 / 1e6,
				requestPrice: 0,
				contextSize: 32768,
				maxOutput: 32000,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
			},
		],
	},
] as const satisfies ModelDefinition[];
