import type { ModelDefinition } from "@/models.js";

export const moonshotModels = [
	{
		id: "kimi-k2",
		name: "Kimi K2",
		description: "Moonshot's Kimi K2 model for general tasks.",
		family: "moonshot",
		releasedAt: new Date("2025-07-11"),
		providers: [
			{
				providerId: "groq",
				modelName: "moonshotai/kimi-k2-instruct",
				inputPrice: 1.0 / 1e6,
				cachedInputPrice: 0.5 / 1e6,
				outputPrice: 3.0 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 16384,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
			{
				providerId: "novita",
				modelName: "moonshotai/kimi-k2-instruct",
				inputPrice: 0.57 / 1e6,
				outputPrice: 2.3 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 131072,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
			{
				providerId: "moonshot",
				modelName: "kimi-k2-0711-preview",
				inputPrice: 0.6 / 1e6,
				outputPrice: 2.5 / 1e6,
				cachedInputPrice: 0.15 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: 128000,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
			{
				providerId: "moonshot",
				modelName: "kimi-k2-0905-preview",
				inputPrice: 0.6 / 1e6,
				outputPrice: 2.5 / 1e6,
				cachedInputPrice: 0.15 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: 128000,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
			{
				providerId: "nebius",
				modelName: "moonshotai/Kimi-K2-Instruct",
				inputPrice: 0.5 / 1e6,
				outputPrice: 2.4 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
			{
				providerId: "bytedance",
				modelName: "kimi-k2-250905",
				inputPrice: 0.6 / 1e6,
				cachedInputPrice: 0.12 / 1e6,
				outputPrice: 2.5 / 1e6,
				requestPrice: 0,
				contextSize: 256000,
				maxOutput: 32768,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: false,
			},
		],
	},
	{
		id: "kimi-k2-thinking",
		name: "Kimi K2 Thinking",
		description: "Kimi K2 with extended thinking capabilities.",
		family: "moonshot",
		releasedAt: new Date("2025-11-06"),
		providers: [
			{
				test: "skip",
				providerId: "kiwillm-kimi",
				modelName: "kimi-k2-thinking",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 262144,
				maxOutput: 262144,
				reasoning: true,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
			{
				providerId: "moonshot",
				modelName: "kimi-k2-thinking",
				inputPrice: 0.6 / 1e6,
				outputPrice: 2.5 / 1e6,
				cachedInputPrice: 0.15 / 1e6,
				requestPrice: 0,
				contextSize: 262144,
				maxOutput: 262144,
				reasoning: true,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
			{
				providerId: "canopywave",
				test: "skip",
				deactivatedAt: new Date("2026-02-06"),
				modelName: "moonshotai/kimi-k2-thinking",
				inputPrice: 0.48 / 1e6,
				cachedInputPrice: 0.12 / 1e6,
				outputPrice: 2.0 / 1e6,
				discount: 0.3,
				requestPrice: 0,
				contextSize: 262144,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
			{
				providerId: "bytedance",
				modelName: "kimi-k2-thinking-251104",
				inputPrice: 0.6 / 1e6,
				cachedInputPrice: 0.12 / 1e6,
				outputPrice: 2.5 / 1e6,
				requestPrice: 0,
				contextSize: 256000,
				maxOutput: 32768,
				reasoning: true,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: false,
			},
		],
	},
	{
		id: "kimi-k2-thinking-turbo",
		name: "Kimi K2 Thinking Turbo",
		description: "Faster turbo variant of Kimi K2 with extended thinking.",
		family: "moonshot",
		releasedAt: new Date("2025-11-06"),
		providers: [
			{
				providerId: "moonshot",
				modelName: "kimi-k2-thinking-turbo",
				inputPrice: 1.15 / 1e6,
				outputPrice: 8.0 / 1e6,
				cachedInputPrice: 0.15 / 1e6,
				requestPrice: 0,
				contextSize: 262144,
				maxOutput: 262144,
				reasoning: true,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "kimi-k2.5",
		name: "Kimi K2.5",
		description:
			"Moonshot's native multimodal model with visual coding and agentic capabilities.",
		family: "moonshot",
		releasedAt: new Date("2026-01-26"),
		providers: [
			{
				test: "skip",
				providerId: "kiwillm-kimi",
				modelName: "kimi-k2.5",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 262144,
				maxOutput: 32768,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
				supportedParameters: [
					"max_tokens",
					"response_format",
					"tools",
					"tool_choice",
				],
			},
			{
				providerId: "moonshot",
				modelName: "kimi-k2.5",
				inputPrice: 0.6 / 1e6,
				outputPrice: 3.0 / 1e6,
				cachedInputPrice: 0.1 / 1e6,
				requestPrice: 0,
				contextSize: 262144,
				maxOutput: 32768,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
				supportedParameters: [
					"max_tokens",
					"response_format",
					"tools",
					"tool_choice",
				],
			},
			{
				providerId: "canopywave",
				test: "skip",
				modelName: "moonshotai/kimi-k2.5",
				inputPrice: 0.5 / 1e6,
				outputPrice: 2.8 / 1e6,
				discount: 0.3,
				requestPrice: 0,
				contextSize: 262144,
				maxOutput: 32768,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
			{
				providerId: "together.ai",
				modelName: "moonshotai/Kimi-K2.5",
				inputPrice: 0.5 / 1e6,
				outputPrice: 2.8 / 1e6,
				requestPrice: 0,
				contextSize: 262144,
				maxOutput: 32768,
				streaming: true,
				vision: true,
				tools: false,
				jsonOutput: false,
			},
		],
	},
] as const satisfies ModelDefinition[];
