import type { ModelDefinition, ProviderModelMapping } from "@/models.js";

const nvidiaWorkerProviderId = "kiwillm-nvidia-worker" as const;

function createProxyMapping(
	modelName: string,
	overrides: Partial<ProviderModelMapping> = {},
): ProviderModelMapping {
	return {
		test: "skip",
		providerId: nvidiaWorkerProviderId,
		modelName,
		inputPrice: 0,
		outputPrice: 0,
		requestPrice: 0,
		contextSize: 8192,
		maxOutput: 4096,
		streaming: true,
		vision: false,
		tools: true,
		jsonOutput: true,
		jsonOutputSchema: true,
		...overrides,
	};
}

function createProxyModel(
	id: string,
	family: ModelDefinition["family"],
	modelName: string,
	overrides: Partial<ModelDefinition> = {},
	mappingOverrides: Partial<ProviderModelMapping> = {},
): ModelDefinition {
	return {
		id,
		name: overrides.name,
		description: overrides.description,
		family,
		releasedAt: overrides.releasedAt,
		aliases: overrides.aliases,
		free: overrides.free,
		rateLimitKind: overrides.rateLimitKind,
		output: overrides.output,
		imageInputRequired: overrides.imageInputRequired,
		stability: overrides.stability,
		supportsSystemRole: overrides.supportsSystemRole,
		providers: [createProxyMapping(modelName, mappingOverrides)],
	};
}

export const nvidiaWorkerProviderAugments: Record<string, ProviderModelMapping[]> = {
	"gemma-2-27b-it": [createProxyMapping("google/gemma-2-27b-it", { contextSize: 8192 })],
	"gemma-2-9b-it": [createProxyMapping("google/gemma-2-9b-it", { contextSize: 8192 })],
	"gemma-3-1b-it": [createProxyMapping("google/gemma-3-1b-it", { contextSize: 8192 })],
	"gemma-3-4b-it": [createProxyMapping("google/gemma-3-4b-it", { contextSize: 8192 })],
	"gemma-3-27b-it": [createProxyMapping("google/gemma-3-27b-it", { contextSize: 8192 })],
	"gemma-3n-e2b-it": [createProxyMapping("google/gemma-3n-e2b-it", { contextSize: 8192 })],
	"gemma-3n-e4b-it": [createProxyMapping("google/gemma-3n-e4b-it", { contextSize: 8192 })],
	"llama-3.1-405b-instruct": [createProxyMapping("meta/llama-3.1-405b-instruct", { contextSize: 131072 })],
	"llama-3.1-70b-instruct": [createProxyMapping("meta/llama-3.1-70b-instruct", { contextSize: 131072 })],
	"llama-3.1-8b-instruct": [createProxyMapping("meta/llama-3.1-8b-instruct", { contextSize: 131072 })],
	"llama-3.2-11b-vision-instruct": [createProxyMapping("meta/llama-3.2-11b-vision-instruct", { contextSize: 8192, vision: true })],
	"llama-3.2-1b-instruct": [createProxyMapping("meta/llama-3.2-1b-instruct", { contextSize: 8192 })],
	"llama-3.2-3b-instruct": [createProxyMapping("meta/llama-3.2-3b-instruct", { contextSize: 8192 })],
	"llama-3.3-70b-instruct": [createProxyMapping("meta/llama-3.3-70b-instruct", { contextSize: 131072 })],
	"llama-guard-4-12b": [createProxyMapping("meta/llama-guard-4-12b", { contextSize: 8192, reasoning: true })],
	"minimax-m2.5": [createProxyMapping("minimaxai/minimax-m2.5", { contextSize: 8192 })],
	"mixtral-8x7b-instruct-v0.1": [createProxyMapping("mistralai/mixtral-8x7b-instruct-v0.1", { contextSize: 8192 })],
	"kimi-k2-instruct": [createProxyMapping("moonshotai/kimi-k2-instruct", { contextSize: 8192 })],
	"kimi-k2-thinking": [createProxyMapping("moonshotai/kimi-k2-thinking", { contextSize: 8192, reasoning: true })],
	"nemotron-3-super-120b-a12b": [createProxyMapping("nvidia/nemotron-3-super-120b-a12b", { contextSize: 131072 })],
	"gpt-oss-120b": [createProxyMapping("openai/gpt-oss-120b", { contextSize: 8192 })],
	"gpt-oss-20b": [createProxyMapping("openai/gpt-oss-20b", { contextSize: 8192 })],
	"qwen3-coder-480b-a35b-instruct": [createProxyMapping("qwen/qwen3-coder-480b-a35b-instruct", { contextSize: 131072 })],
	"qwen3-next-80b-a3b-instruct": [createProxyMapping("qwen/qwen3-next-80b-a3b-instruct", { contextSize: 8192 })],
	"qwen3-next-80b-a3b-thinking": [createProxyMapping("qwen/qwen3-next-80b-a3b-thinking", { contextSize: 8192, reasoning: true })],
	"qwen3.5-397b-a17b": [createProxyMapping("qwen/qwen3.5-397b-a17b", { contextSize: 131072 })],
	"step-3.5-flash": [createProxyMapping("stepfun-ai/step-3.5-flash", { contextSize: 8192 })],
};

export const nvidiaWorkerModels = [
	createProxyModel("dracarys-llama-3.1-70b-instruct", "meta", "abacusai/dracarys-llama-3.1-70b-instruct", { name: "Dracarys Llama 3.1 70B", description: "Dracarys Llama 3.1 70B exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 131072 }),
	createProxyModel("jamba-1.5-mini-instruct", "ai21", "ai21labs/jamba-1.5-mini-instruct", { name: "Jamba 1.5 Mini", description: "Jamba 1.5 Mini exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("baichuan2-13b-chat", "baichuan", "baichuan-inc/baichuan2-13b-chat", { name: "Baichuan2 13B Chat", description: "Baichuan2 13B Chat exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("deepseek-r1-distill-llama-8b", "deepseek", "deepseek-ai/deepseek-r1-distill-llama-8b", { name: "DeepSeek R1 Distill 8B", description: "DeepSeek R1 Distill 8B exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192, reasoning: true, reasoningOutput: "omit" }),
	createProxyModel("deepseek-v3.1-terminus", "deepseek", "deepseek-ai/deepseek-v3.1-terminus", { name: "DeepSeek V3.1 Terminus", description: "DeepSeek V3.1 Terminus exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 131072 }),
	createProxyModel("gemma-2-2b-it", "google", "google/gemma-2-2b-it", { name: "Gemma 2 2B", description: "Gemma 2 2B exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("gemma-4-31b-it", "google", "google/gemma-4-31b-it", { name: "Gemma 4 31B", description: "Gemma 4 31B exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("gemma-7b", "google", "google/gemma-7b", { name: "Gemma 7B", description: "Gemma 7B exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("shieldgemma-9b", "google", "google/shieldgemma-9b", { name: "ShieldGemma 9B", description: "ShieldGemma 9B exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("gemma-2-9b-cpt-sahabatai-instruct", "google", "gotocompany/gemma-2-9b-cpt-sahabatai-instruct", { name: "Gemma 2 Sahabatai 9B", description: "Gemma 2 Sahabatai 9B exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("granite-guardian-3.0-8b", "ibm", "ibm/granite-guardian-3.0-8b", { name: "Granite Guardian 8B", description: "Granite Guardian 8B exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192, reasoning: true }),
	createProxyModel("italia_10b_instruct_16k", "igenius", "igenius/italia_10b_instruct_16k", { name: "Italia 10B", description: "Italia 10B exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 16384 }),
	createProxyModel("llama-3.1-swallow-70b-instruct-v0.1", "meta", "institute-of-science-tokyo/llama-3.1-swallow-70b-instruct-v0.1", { name: "Llama 3.1 Swallow 70B", description: "Llama 3.1 Swallow 70B exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 131072 }),
	createProxyModel("llama-3.1-swallow-8b-instruct-v0.1", "meta", "institute-of-science-tokyo/llama-3.1-swallow-8b-instruct-v0.1", { name: "Llama 3.1 Swallow 8B", description: "Llama 3.1 Swallow 8B exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 131072 }),
	createProxyModel("marin-8b-instruct", "marin", "marin/marin-8b-instruct", { name: "Marin 8B", description: "Marin 8B exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("breeze-7b-instruct", "mediatek", "mediatek/breeze-7b-instruct", { name: "Breeze 7B", description: "Breeze 7B exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("llama-3.2-90b-vision-instruct", "meta", "meta/llama-3.2-90b-vision-instruct", { name: "Llama 3.2 Vision 90B", description: "Llama 3.2 Vision 90B exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192, vision: true }),
	createProxyModel("llama-4-maverick-17b-128e-instruct", "meta", "meta/llama-4-maverick-17b-128e-instruct", { name: "Llama 4 Maverick 17B", description: "Llama 4 Maverick 17B exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 131072 }),
	createProxyModel("llama3-70b-instruct", "meta", "meta/llama3-70b-instruct", { name: "Llama 3 70B", description: "Llama 3 70B exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("llama3-8b-instruct", "meta", "meta/llama3-8b-instruct", { name: "Llama 3 8B", description: "Llama 3 8B exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("phi-3-medium-128k-instruct", "microsoft", "microsoft/phi-3-medium-128k-instruct", { name: "Phi-3 Medium 128K", description: "Phi-3 Medium 128K exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 131072 }),
	createProxyModel("phi-3-medium-4k-instruct", "microsoft", "microsoft/phi-3-medium-4k-instruct", { name: "Phi-3 Medium 4K", description: "Phi-3 Medium 4K exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 4096 }),
	createProxyModel("phi-3-mini-128k-instruct", "microsoft", "microsoft/phi-3-mini-128k-instruct", { name: "Phi-3 Mini 128K", description: "Phi-3 Mini 128K exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 131072 }),
	createProxyModel("phi-3-mini-4k-instruct", "microsoft", "microsoft/phi-3-mini-4k-instruct", { name: "Phi-3 Mini 4K", description: "Phi-3 Mini 4K exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 4096 }),
	createProxyModel("phi-3-small-128k-instruct", "microsoft", "microsoft/phi-3-small-128k-instruct", { name: "Phi-3 Small 128K", description: "Phi-3 Small 128K exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 131072 }),
	createProxyModel("phi-3-small-8k-instruct", "microsoft", "microsoft/phi-3-small-8k-instruct", { name: "Phi-3 Small 8K", description: "Phi-3 Small 8K exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("phi-3.5-mini-instruct", "microsoft", "microsoft/phi-3.5-mini-instruct", { name: "Phi-3.5 Mini", description: "Phi-3.5 Mini exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 131072 }),
	createProxyModel("phi-3.5-vision-instruct", "microsoft", "microsoft/phi-3.5-vision-instruct", { name: "Phi-3.5 Vision", description: "Phi-3.5 Vision exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 131072, vision: true }),
	createProxyModel("phi-4-mini-flash-reasoning", "microsoft", "microsoft/phi-4-mini-flash-reasoning", { name: "Phi-4 Mini Flash", description: "Phi-4 Mini Flash exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192, reasoning: true }),
	createProxyModel("phi-4-mini-instruct", "microsoft", "microsoft/phi-4-mini-instruct", { name: "Phi-4 Mini", description: "Phi-4 Mini exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("phi-4-multimodal-instruct", "microsoft", "microsoft/phi-4-multimodal-instruct", { name: "Phi-4 Multimodal", description: "Phi-4 Multimodal exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("devstral-2-123b-instruct-2512", "mistral", "mistralai/devstral-2-123b-instruct-2512", { name: "Devstral 2 123B", description: "Devstral 2 123B exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 131072 }),
	createProxyModel("magistral-small-2506", "mistral", "mistralai/magistral-small-2506", { name: "Magistral Small", description: "Magistral Small exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("mamba-codestral-7b-v0.1", "mistral", "mistralai/mamba-codestral-7b-v0.1", { name: "Mamba Codestral 7B", description: "Mamba Codestral 7B exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("mathstral-7b-v0.1", "mistral", "mistralai/mathstral-7b-v0.1", { name: "Mathstral 7B", description: "Mathstral 7B exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("ministral-14b-instruct-2512", "mistral", "mistralai/ministral-14b-instruct-2512", { name: "Ministral 14B", description: "Ministral 14B exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("mistral-7b-instruct-v0.2", "mistral", "mistralai/mistral-7b-instruct-v0.2", { name: "Mistral 7B v0.2", description: "Mistral 7B v0.2 exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("mistral-7b-instruct-v0.3", "mistral", "mistralai/mistral-7b-instruct-v0.3", { name: "Mistral 7B v0.3", description: "Mistral 7B v0.3 exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("mistral-large-3-675b-instruct-2512", "mistral", "mistralai/mistral-large-3-675b-instruct-2512", { name: "Mistral Large 3 675B", description: "Mistral Large 3 675B exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 131072 }),
	createProxyModel("mistral-nemotron", "mistral", "mistralai/mistral-nemotron", { name: "Mistral Nemotron", description: "Mistral Nemotron exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("mistral-small-24b-instruct", "mistral", "mistralai/mistral-small-24b-instruct", { name: "Mistral Small 24B", description: "Mistral Small 24B exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("mistral-small-4-119b-2603", "mistral", "mistralai/mistral-small-4-119b-2603", { name: "Mistral Small 4 119B", description: "Mistral Small 4 119B exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("mixtral-8x22b-instruct-v0.1", "mistral", "mistralai/mixtral-8x22b-instruct-v0.1", { name: "Mixtral 8x22B", description: "Mixtral 8x22B exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 65536 }),
	createProxyModel("kimi-k2-instruct-0905", "moonshot", "moonshotai/kimi-k2-instruct-0905", { name: "Kimi K2 Instruct 0905", description: "Kimi K2 Instruct 0905 exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("gliner-pii", "nvidia", "nvidia/gliner-pii", { name: "GLiNER PII", description: "GLiNER PII exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("llama-3.1-nemoguard-8b-content-safety", "nvidia", "nvidia/llama-3.1-nemoguard-8b-content-safety", { name: "NemoGuard Content Safety", description: "NemoGuard Content Safety exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 131072, reasoning: true }),
	createProxyModel("llama-3.1-nemoguard-8b-topic-control", "nvidia", "nvidia/llama-3.1-nemoguard-8b-topic-control", { name: "NemoGuard Topic Control", description: "NemoGuard Topic Control exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 131072, reasoning: true }),
	createProxyModel("llama-3.1-nemotron-70b-reward", "nvidia", "nvidia/llama-3.1-nemotron-70b-reward", { name: "Nemotron 70B Reward", description: "Nemotron 70B Reward exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 131072, reasoning: true }),
	createProxyModel("llama-3.1-nemotron-nano-8b-v1", "nvidia", "nvidia/llama-3.1-nemotron-nano-8b-v1", { name: "Nemotron Nano 8B", description: "Nemotron Nano 8B exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 131072 }),
	createProxyModel("llama-3.1-nemotron-nano-vl-8b-v1", "nvidia", "nvidia/llama-3.1-nemotron-nano-vl-8b-v1", { name: "Nemotron Nano VL 8B", description: "Nemotron Nano VL 8B exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 131072, vision: true }),
	createProxyModel("llama-3.1-nemotron-safety-guard-8b-v3", "nvidia", "nvidia/llama-3.1-nemotron-safety-guard-8b-v3", { name: "Nemotron Safety Guard", description: "Nemotron Safety Guard exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 131072, reasoning: true }),
	createProxyModel("llama-3.1-nemotron-ultra-253b-v1", "nvidia", "nvidia/llama-3.1-nemotron-ultra-253b-v1", { name: "Nemotron Ultra 253B", description: "Nemotron Ultra 253B exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 131072 }),
	createProxyModel("llama-3.3-nemotron-super-49b-v1", "nvidia", "nvidia/llama-3.3-nemotron-super-49b-v1", { name: "Nemotron Super 49B v1", description: "Nemotron Super 49B v1 exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 131072 }),
	createProxyModel("llama-3.3-nemotron-super-49b-v1.5", "nvidia", "nvidia/llama-3.3-nemotron-super-49b-v1.5", { name: "Nemotron Super 49B v1.5", description: "Nemotron Super 49B v1.5 exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 131072 }),
	createProxyModel("llama3-chatqa-1.5-8b", "nvidia", "nvidia/llama3-chatqa-1.5-8b", { name: "Llama3 ChatQA 8B", description: "Llama3 ChatQA 8B exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("nemotron-3-nano-30b-a3b", "nvidia", "nvidia/nemotron-3-nano-30b-a3b", { name: "Nemotron 3 Nano 30B", description: "Nemotron 3 Nano 30B exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("nemotron-4-mini-hindi-4b-instruct", "nvidia", "nvidia/nemotron-4-mini-hindi-4b-instruct", { name: "Nemotron Hindi 4B", description: "Nemotron Hindi 4B exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("nemotron-content-safety-reasoning-4b", "nvidia", "nvidia/nemotron-content-safety-reasoning-4b", { name: "Nemotron Safety Reasoning", description: "Nemotron Safety Reasoning exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192, reasoning: true }),
	createProxyModel("nemotron-mini-4b-instruct", "nvidia", "nvidia/nemotron-mini-4b-instruct", { name: "Nemotron Mini 4B", description: "Nemotron Mini 4B exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("nemotron-nano-12b-v2-vl", "nvidia", "nvidia/nemotron-nano-12b-v2-vl", { name: "Nemotron Nano 12B VL", description: "Nemotron Nano 12B VL exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("nvidia-nemotron-nano-9b-v2", "nvidia", "nvidia/nvidia-nemotron-nano-9b-v2", { name: "Nemotron Nano 9B v2", description: "Nemotron Nano 9B v2 exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("riva-translate-4b-instruct-v1.1", "nvidia", "nvidia/riva-translate-4b-instruct-v1.1", { name: "Riva Translate 4B", description: "Riva Translate 4B exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("teuken-7b-instruct-commercial-v0.4", "opengptx", "opengpt-x/teuken-7b-instruct-commercial-v0.4", { name: "Teuken 7B", description: "Teuken 7B exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("qwen2-7b-instruct", "alibaba", "qwen/qwen2-7b-instruct", { name: "Qwen2 7B", description: "Qwen2 7B exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("qwen2.5-7b-instruct", "alibaba", "qwen/qwen2.5-7b-instruct", { name: "Qwen2.5 7B", description: "Qwen2.5 7B exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("qwen2.5-coder-32b-instruct", "alibaba", "qwen/qwen2.5-coder-32b-instruct", { name: "Qwen2.5 Coder 32B", description: "Qwen2.5 Coder 32B exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("qwen2.5-coder-7b-instruct", "alibaba", "qwen/qwen2.5-coder-7b-instruct", { name: "Qwen2.5 Coder 7B", description: "Qwen2.5 Coder 7B exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("rakutenai-7b-chat", "rakuten", "rakuten/rakutenai-7b-chat", { name: "RakutenAI 7B Chat", description: "RakutenAI 7B Chat exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("rakutenai-7b-instruct", "rakuten", "rakuten/rakutenai-7b-instruct", { name: "RakutenAI 7B Instruct", description: "RakutenAI 7B Instruct exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("sarvam-m", "sarvam", "sarvamai/sarvam-m", { name: "Sarvam M", description: "Sarvam M exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("bielik-11b-v2.3-instruct", "speakleash", "speakleash/bielik-11b-v2.3-instruct", { name: "Bielik 11B v2.3", description: "Bielik 11B v2.3 exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("bielik-11b-v2.6-instruct", "speakleash", "speakleash/bielik-11b-v2.6-instruct", { name: "Bielik 11B v2.6", description: "Bielik 11B v2.6 exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("stockmark-2-100b-instruct", "stockmark", "stockmark/stockmark-2-100b-instruct", { name: "Stockmark 2 100B", description: "Stockmark 2 100B exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("chatglm3-6b", "glm", "thudm/chatglm3-6b", { name: "ChatGLM3 6B", description: "ChatGLM3 6B exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("falcon3-7b-instruct", "tiiuae", "tiiuae/falcon3-7b-instruct", { name: "Falcon3 7B", description: "Falcon3 7B exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("llama-3-swallow-70b-instruct-v0.1", "meta", "tokyotech-llm/llama-3-swallow-70b-instruct-v0.1", { name: "Llama 3 Swallow 70B", description: "Llama 3 Swallow 70B exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("solar-10.7b-instruct", "upstage", "upstage/solar-10.7b-instruct", { name: "Solar 10.7B", description: "Solar 10.7B exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("eurollm-9b-instruct", "utter", "utter-project/eurollm-9b-instruct", { name: "EuroLLM 9B", description: "EuroLLM 9B exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("llama-3-taiwan-70b-instruct", "meta", "yentinglin/llama-3-taiwan-70b-instruct", { name: "Llama 3 Taiwan 70B", description: "Llama 3 Taiwan 70B exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192 }),
	createProxyModel("glm4.7", "glm", "z-ai/glm4.7", { name: "GLM4.7", description: "GLM4.7 exposed by the NVIDIA KiwiLLM worker." }, { contextSize: 8192, reasoning: true, reasoningOutput: "omit" }),
] as const satisfies ModelDefinition[];
