import type { ModelDefinition } from "@/models.js";

export const openaiModels = [
	{
		id: "gpt-4o-mini",
		name: "GPT-4o Mini",
		description:
			"Affordable small model for fast, lightweight tasks with text and vision capabilities.",
		family: "openai",
		releasedAt: new Date("2024-07-18"),
		providers: [
			{
				providerId: "openai",
				modelName: "gpt-4o-mini",
				inputPrice: 0.15 / 1e6,
				outputPrice: 0.6 / 1e6,
				cachedInputPrice: 0.075 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: 16384,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutputSchema: true,
				jsonOutput: true,
			},
			{
				providerId: "azure",
				stability: "unstable" as const,
				modelName: "gpt-4o-mini",
				inputPrice: 0.15 / 1e6,
				outputPrice: 0.6 / 1e6,
				cachedInputPrice: 0.075 / 1e6,
				contextSize: 128000,
				maxOutput: 16384,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
				deprecatedAt: new Date("2026-01-09"),
				deactivatedAt: new Date("2026-03-31"),
			},
			{
				test: "skip",
				providerId: "kiwillm-claude-talkai",
				modelName: "gpt-4o-mini",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: 16384,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "kiwillm-grok-proxy",
				modelName: "gpt-4o-mini",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: 16384,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "gpt-4o-search-preview",
		name: "GPT-4o Search Preview",
		description:
			"GPT-4o with native web search capabilities for up-to-date information.",
		family: "openai",
		releasedAt: new Date("2024-10-01"),
		providers: [
			{
				providerId: "openai",
				modelName: "gpt-4o-search-preview",
				inputPrice: 2.5 / 1e6,
				outputPrice: 10.0 / 1e6,
				requestPrice: 0,
				webSearch: true,
				webSearchPrice: 0.025, // $25 per 1000 searches for non-reasoning models
				contextSize: 128000,
				maxOutput: 16384,
				streaming: true,
				vision: true,
				tools: false, // Search models don't support additional tools
				jsonOutput: false,
				supportedParameters: ["max_tokens", "response_format"],
			},
		],
	},
	{
		id: "gpt-4o-mini-search-preview",
		name: "GPT-4o Mini Search Preview",
		description:
			"Cost-effective GPT-4o Mini with native web search capabilities.",
		family: "openai",
		releasedAt: new Date("2024-10-01"),
		providers: [
			{
				providerId: "openai",
				modelName: "gpt-4o-mini-search-preview",
				inputPrice: 0.15 / 1e6,
				outputPrice: 0.6 / 1e6,
				requestPrice: 0,
				webSearch: true,
				webSearchPrice: 0.025, // $25 per 1000 searches for non-reasoning models
				contextSize: 128000,
				maxOutput: 16384,
				streaming: true,
				vision: true,
				tools: false, // Search models don't support additional tools
				jsonOutput: false,
				supportedParameters: ["max_tokens", "response_format"],
			},
		],
	},
	{
		id: "gpt-4",
		name: "GPT-4",
		description:
			"Original GPT-4 model with strong reasoning and tool use capabilities.",
		family: "openai",
		releasedAt: new Date("2023-03-14"),
		providers: [
			{
				test: "skip",
				providerId: "openai",
				modelName: "gpt-4",
				inputPrice: 30.0 / 1e6,
				outputPrice: 60.0 / 1e6,
				requestPrice: 0,
				contextSize: 8192,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
				supportedParameters: [
					"temperature",
					"max_tokens",
					"top_p",
					"frequency_penalty",
					"presence_penalty",
					"response_format",
					"tools",
					"tool_choice",
				],
				jsonOutput: false,
			},
			{
				test: "skip",
				providerId: "azure",
				stability: "unstable" as const,
				modelName: "gpt-4",
				inputPrice: 30.0 / 1e6,
				outputPrice: 60.0 / 1e6,
				contextSize: 8192,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: false,
			},
			{
				test: "skip",
				providerId: "kiwillm-claude-talkai",
				modelName: "gpt-4",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 8192,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "kiwillm-chatbot-ai",
				modelName: "gpt-4",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 8192,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "kiwillm-claude-v3xg",
				modelName: "gpt-4",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 8192,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "gpt-4o",
		name: "GPT-4o",
		description:
			"Multimodal flagship model with vision, fast responses, and tool support.",
		family: "openai",
		releasedAt: new Date("2024-05-13"),
		providers: [
			{
				providerId: "openai",
				modelName: "gpt-4o",
				inputPrice: 2.5 / 1e6,
				outputPrice: 10.0 / 1e6,
				cachedInputPrice: 1.25 / 1e6,
				requestPrice: 0,
				imageInputPrice: 0.00553,
				contextSize: 128000,
				maxOutput: 16384,
				streaming: true,
				vision: true,
				tools: true,
				webSearch: true, // Supports web_search tool via Responses API
				jsonOutputSchema: true,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "azure",
				stability: "unstable" as const,
				modelName: "gpt-4o",
				inputPrice: 2.5 / 1e6,
				outputPrice: 10.0 / 1e6,
				cachedInputPrice: 1.25 / 1e6,
				imageInputPrice: 0.00553,
				contextSize: 128000,
				maxOutput: 16384,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "kiwillm-claude-talkai",
				modelName: "gpt-4o",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: 16384,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "kiwillm-grok-proxy",
				modelName: "gpt-4o",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: 16384,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "gpt-3.5-turbo",
		name: "GPT-3.5 Turbo",
		description:
			"Fast and cost-effective model for simple tasks and conversational applications.",
		family: "openai",
		releasedAt: new Date("2022-11-30"),
		providers: [
			{
				providerId: "openai",
				modelName: "gpt-3.5-turbo",
				inputPrice: 0.5 / 1e6,
				outputPrice: 1.5 / 1e6,
				requestPrice: 0,
				contextSize: 16385,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutputSchema: false,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "azure",
				stability: "unstable" as const,
				modelName: "gpt-35-turbo",
				inputPrice: 0.5 / 1e6,
				outputPrice: 1.5 / 1e6,
				contextSize: 16385,
				maxOutput: 4096,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "kiwillm-claude-talkai",
				modelName: "gpt-3.5-turbo",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 16385,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "kiwillm-chatbot-ai",
				modelName: "gpt-3.5-turbo",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 16385,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "gpt-3.5-turbo-16k",
		name: "GPT-3.5 Turbo 16K",
		description:
			"Extended-context GPT-3.5 Turbo snapshot exposed through the Chatbot AI worker.",
		family: "openai",
		providers: [
			{
				test: "skip",
				providerId: "kiwillm-chatbot-ai",
				modelName: "gpt-3.5-turbo-16k",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 16384,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "gpt-4-turbo",
		name: "GPT-4 Turbo",
		description:
			"Enhanced GPT-4 with vision capabilities and improved performance.",
		family: "openai",
		releasedAt: new Date("2023-11-06"),
		providers: [
			{
				test: "skip",
				providerId: "openai",
				modelName: "gpt-4-turbo",
				inputPrice: 10.0 / 1e6,
				outputPrice: 30.0 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutputSchema: true,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "azure",
				stability: "unstable" as const,
				modelName: "gpt-4-turbo",
				inputPrice: 10.0 / 1e6,
				outputPrice: 30.0 / 1e6,
				contextSize: 128000,
				maxOutput: 4096,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "kiwillm-claude-talkai",
				modelName: "gpt-4-turbo",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "gpt-4.1",
		name: "GPT-4.1",
		description: "Updated GPT-4 with vision support and parallel tool calls.",
		family: "openai",
		releasedAt: new Date("2025-04-14"),
		providers: [
			{
				providerId: "openai",
				modelName: "gpt-4.1",
				inputPrice: 2.0 / 1e6,
				outputPrice: 8.0 / 1e6,
				cachedInputPrice: 0.5 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: undefined,
				streaming: true,
				vision: true,
				tools: true,
				parallelToolCalls: true,
				jsonOutputSchema: true,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "azure",
				stability: "unstable" as const,
				modelName: "gpt-4.1",
				inputPrice: 2.0 / 1e6,
				outputPrice: 8.0 / 1e6,
				cachedInputPrice: 0.5 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: undefined,
				streaming: true,
				vision: true,
				tools: true,
				parallelToolCalls: true,
				jsonOutputSchema: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "o1",
		name: "o1",
		description:
			"Advanced reasoning model that thinks before responding for complex problem-solving.",
		family: "openai",
		releasedAt: new Date("2024-09-12"),
		providers: [
			{
				test: "skip",
				providerId: "openai",
				modelName: "o1",
				inputPrice: 15.0 / 1e6,
				outputPrice: 60.0 / 1e6,
				cachedInputPrice: 7.5 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: undefined,
				streaming: true,
				vision: true,
				reasoning: true,
				tools: false,
				jsonOutputSchema: true,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "azure",
				stability: "unstable" as const,
				modelName: "o1",
				inputPrice: 15.0 / 1e6,
				outputPrice: 60.0 / 1e6,
				cachedInputPrice: 7.5 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: undefined,
				streaming: true,
				vision: true,
				reasoning: true,
				tools: false,
				jsonOutputSchema: true,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "kiwillm-claude-talkai",
				modelName: "o1",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: undefined,
				streaming: true,
				vision: true,
				reasoning: true,
				tools: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "o1-mini",
		name: "o1 Mini",
		description:
			"Smaller, faster reasoning model optimized for coding and math tasks.",
		family: "openai",
		releasedAt: new Date("2024-09-12"),
		providers: [
			{
				stability: "unstable" as const,
				providerId: "openai",
				modelName: "o1-mini",
				inputPrice: 1.1 / 1e6,
				outputPrice: 4.4 / 1e6,
				cachedInputPrice: 0.55 / 1e6,
				requestPrice: 0,
				deactivatedAt: new Date("2025-10-27"),
				contextSize: 128000,
				maxOutput: undefined,
				streaming: false,
				vision: false,
				tools: false,
				reasoning: false,
				supportsResponsesApi: false,
				jsonOutput: false,
			},
			{
				test: "skip",
				providerId: "azure",
				stability: "unstable" as const,
				modelName: "o1-mini",
				inputPrice: 1.1 / 1e6,
				outputPrice: 4.4 / 1e6,
				cachedInputPrice: 0.55 / 1e6,
				requestPrice: 0,
				deactivatedAt: new Date("2025-10-27"),
				contextSize: 128000,
				maxOutput: undefined,
				streaming: false,
				vision: false,
				tools: false,
				reasoning: false,
				supportsResponsesApi: false,
				jsonOutput: false,
			},
			{
				test: "skip",
				providerId: "kiwillm-claude-talkai",
				modelName: "o1-mini",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				reasoning: true,
				jsonOutput: true,
			},
		],
		supportsSystemRole: false,
	},
	{
		id: "gpt-4.1-mini",
		name: "GPT-4.1 Mini",
		description: "Compact version of GPT-4.1 with vision and tool support.",
		family: "openai",
		releasedAt: new Date("2025-04-14"),
		providers: [
			{
				providerId: "openai",
				modelName: "gpt-4.1-mini",
				inputPrice: 0.4 / 1e6,
				outputPrice: 1.6 / 1e6,
				cachedInputPrice: 0.1 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: undefined,
				streaming: true,
				vision: true,
				tools: true,
				parallelToolCalls: true,
				jsonOutputSchema: true,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "azure",
				stability: "unstable" as const,
				modelName: "gpt-4.1-mini",
				inputPrice: 0.4 / 1e6,
				outputPrice: 1.6 / 1e6,
				cachedInputPrice: 0.1 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: undefined,
				streaming: true,
				vision: true,
				tools: true,
				parallelToolCalls: true,
				jsonOutputSchema: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "gpt-4.1-nano",
		name: "GPT-4.1 Nano",
		description:
			"Ultra-lightweight GPT-4.1 variant for high-volume, cost-sensitive applications.",
		family: "openai",
		releasedAt: new Date("2025-04-14"),
		providers: [
			{
				providerId: "openai",
				modelName: "gpt-4.1-nano",
				inputPrice: 0.1 / 1e6,
				outputPrice: 0.4 / 1e6,
				cachedInputPrice: 0.025 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: undefined,
				streaming: true,
				vision: true,
				tools: true,
				parallelToolCalls: true,
				jsonOutputSchema: true,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "azure",
				stability: "unstable" as const,
				modelName: "gpt-4.1-nano",
				inputPrice: 0.1 / 1e6,
				outputPrice: 0.4 / 1e6,
				cachedInputPrice: 0.025 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: undefined,
				streaming: true,
				vision: true,
				tools: true,
				parallelToolCalls: true,
				jsonOutputSchema: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "o3",
		name: "o3",
		description:
			"Next-generation reasoning model with enhanced problem-solving capabilities.",
		family: "openai",
		releasedAt: new Date("2025-06-01"),
		providers: [
			{
				providerId: "openai",
				modelName: "o3",
				inputPrice: 2 / 1e6,
				outputPrice: 8 / 1e6,
				cachedInputPrice: 0.5 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: undefined,
				streaming: false,
				vision: true,
				tools: false,
				jsonOutputSchema: true,
				jsonOutput: true,
				supportedParameters: ["reasoning_effort", "response_format"],
			},
			{
				test: "skip",
				providerId: "azure",
				stability: "unstable" as const,
				modelName: "o3",
				inputPrice: 2 / 1e6,
				outputPrice: 8 / 1e6,
				cachedInputPrice: 0.5 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: undefined,
				streaming: false,
				vision: true,
				tools: false,
				jsonOutputSchema: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "o3-mini",
		name: "o3 Mini",
		description:
			"Compact o3 reasoning model balancing performance and cost for complex tasks.",
		family: "openai",
		releasedAt: new Date("2025-06-01"),
		providers: [
			{
				providerId: "openai",
				modelName: "o3-mini",
				inputPrice: 1.1 / 1e6,
				outputPrice: 4.4 / 1e6,
				cachedInputPrice: 0.55 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutputSchema: true,
				jsonOutput: true,
				supportedParameters: ["reasoning_effort", "response_format"],
			},
			{
				test: "skip",
				providerId: "azure",
				stability: "unstable" as const,
				modelName: "o3-mini",
				inputPrice: 1.1 / 1e6,
				outputPrice: 4.4 / 1e6,
				cachedInputPrice: 0.55 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutputSchema: true,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "kiwillm-claude-talkai",
				modelName: "o3-mini",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				reasoning: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "chatgpt-4o-latest",
		name: "ChatGPT-4o Latest",
		description:
			"Latest ChatGPT-4o snapshot exposed through the Claude TalkAI worker.",
		family: "openai",
		providers: [
			{
				test: "skip",
				providerId: "kiwillm-claude-talkai",
				modelName: "chatgpt-4o-latest",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: 16384,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "gpt-4-turbo-preview",
		name: "GPT-4 Turbo Preview",
		description:
			"Preview snapshot of GPT-4 Turbo exposed through the Claude TalkAI worker.",
		family: "openai",
		providers: [
			{
				test: "skip",
				providerId: "kiwillm-claude-talkai",
				modelName: "gpt-4-turbo-preview",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "gpt-4-32k",
		name: "GPT-4 32K",
		description:
			"Legacy GPT-4 32K snapshot exposed through the Claude TalkAI worker.",
		family: "openai",
		providers: [
			{
				test: "skip",
				providerId: "kiwillm-claude-talkai",
				modelName: "gpt-4-32k",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 32768,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "gpt-4-vision-preview",
		name: "GPT-4 Vision Preview",
		description:
			"Preview multimodal GPT-4 snapshot exposed through the Claude TalkAI worker.",
		family: "openai",
		providers: [
			{
				test: "skip",
				providerId: "kiwillm-claude-talkai",
				modelName: "gpt-4-vision-preview",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: 4096,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "gpt-3.5-turbo-0125",
		name: "GPT-3.5 Turbo 0125",
		description:
			"0125 snapshot of GPT-3.5 Turbo exposed through the Claude TalkAI worker.",
		family: "openai",
		providers: [
			{
				test: "skip",
				providerId: "kiwillm-claude-talkai",
				modelName: "gpt-3.5-turbo-0125",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 16385,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "o1-preview",
		name: "o1 Preview",
		description:
			"Preview snapshot of the o1 reasoning model exposed through the Claude TalkAI worker.",
		family: "openai",
		providers: [
			{
				test: "skip",
				providerId: "kiwillm-claude-talkai",
				modelName: "o1-preview",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				reasoning: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "o4-mini",
		name: "o4 Mini",
		description:
			"Compact reasoning model with strong performance and efficient inference.",
		family: "openai",
		releasedAt: new Date("2025-04-16"),
		providers: [
			{
				providerId: "openai",
				modelName: "o4-mini",
				inputPrice: 1.1 / 1e6,
				outputPrice: 4.4 / 1e6,
				cachedInputPrice: 0.275 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: undefined,
				streaming: true,
				vision: true,
				tools: true,
				reasoning: true,
				jsonOutputSchema: true,
				jsonOutput: true,
				supportedParameters: ["reasoning_effort", "response_format"],
			},
			{
				test: "skip",
				providerId: "azure",
				stability: "unstable" as const,
				modelName: "o4-mini",
				inputPrice: 1.1 / 1e6,
				outputPrice: 4.4 / 1e6,
				cachedInputPrice: 0.275 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: undefined,
				streaming: true,
				vision: true,
				tools: true,
				reasoning: true,
				jsonOutputSchema: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "gpt-oss-120b",
		name: "GPT OSS 120B",
		description:
			"Open-source 120B parameter model with reasoning capabilities via Groq inference.",
		family: "openai",
		releasedAt: new Date("2025-08-05"),
		providers: [
			{
				providerId: "groq",
				modelName: "openai/gpt-oss-120b",
				inputPrice: 0.15 / 1e6,
				outputPrice: 0.75 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 32766,
				streaming: true,
				vision: false,
				tools: true,
				reasoning: true,
				jsonOutput: true,
			},
			{
				// Cerebras: FP16/FP8 (weights only)
				providerId: "cerebras",
				modelName: "gpt-oss-120b",
				inputPrice: 0.35 / 1e6,
				outputPrice: 0.75 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 32768,
				streaming: true,
				vision: false,
				tools: true,
				reasoning: true,
				jsonOutput: true,
				supportedParameters: [
					"temperature",
					"max_tokens",
					"top_p",
					"response_format",
					"tools",
					"tool_choice",
				],
			},
			{
				test: "skip",
				providerId: "nanogpt",
				modelName: "openai/gpt-oss-120b",
				inputPrice: 0.05 / 1e6,
				outputPrice: 0.25 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 32766,
				streaming: true,
				vision: false,
				tools: true,
				reasoning: true,
				jsonOutput: true,
			},
			{
				providerId: "bytedance",
				modelName: "gpt-oss-120b-250805",
				inputPrice: 0.1 / 1e6,
				cachedInputPrice: 0.02 / 1e6,
				outputPrice: 0.5 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: 32000,
				streaming: true,
				vision: false,
				tools: true,
				reasoning: true,
				jsonOutput: false, // BytePlus doesn't support response_format
			},
			{
				test: "skip",
				providerId: "kiwillm-gpt-oss-worker",
				modelName: "gpt-oss-120b",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 32768,
				streaming: true,
				vision: false,
				tools: true,
				reasoning: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "gpt-oss-20b",
		name: "GPT OSS 20B",
		description:
			"Lightweight open-source 20B model with reasoning support for efficient inference.",
		family: "openai",
		releasedAt: new Date("2025-08-05"),
		providers: [
			{
				providerId: "groq",
				modelName: "openai/gpt-oss-20b",
				inputPrice: 0.1 / 1e6,
				outputPrice: 0.5 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 32766,
				streaming: true,
				vision: false,
				tools: true,
				reasoning: true,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "nanogpt",
				modelName: "openai/gpt-oss-20b",
				inputPrice: 0.04 / 1e6,
				outputPrice: 0.15 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 32766,
				streaming: true,
				vision: false,
				tools: true,
				reasoning: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "gpt-5",
		name: "GPT-5",
		description:
			"Latest flagship model with reasoning, vision, and enhanced capabilities.",
		family: "openai",
		// Based on August 2025 launch from AI timeline:
		// https://raw.githubusercontent.com/NHLOCAL/AiTimeline/refs/heads/main/_data/timeline.yml
		releasedAt: new Date("2025-08-01"),
		providers: [
			{
				providerId: "openai",
				modelName: "gpt-5",
				inputPrice: 1.25 / 1e6,
				outputPrice: 10.0 / 1e6,
				cachedInputPrice: 0.125 / 1e6,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 128000,
				reasoning: true,
				streaming: true,
				vision: true,
				tools: true,
				webSearch: true, // Supports web_search tool via Responses API
				webSearchPrice: 0.01, // $10 per 1000 searches for reasoning models
				supportsResponsesApi: true,
				jsonOutputSchema: true,
				supportedParameters: [
					"temperature",
					"top_p",
					"frequency_penalty",
					"presence_penalty",
					"response_format",
					"tools",
					"tool_choice",
				],
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "kiwillm-free-ai-hub",
				modelName: "openai/gpt-5",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 128000,
				reasoning: true,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
				jsonOutputSchema: true,
			},
			{
				test: "skip",
				providerId: "azure",
				stability: "unstable" as const,
				modelName: "gpt-5",
				inputPrice: 1.25 / 1e6,
				outputPrice: 10.0 / 1e6,
				cachedInputPrice: 0.125 / 1e6,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 128000,
				reasoning: true,
				supportsResponsesApi: true,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutputSchema: true,
				supportedParameters: [
					"temperature",
					"top_p",
					"frequency_penalty",
					"presence_penalty",
					"response_format",
					"tools",
					"tool_choice",
				],
				jsonOutput: true,
			},
		],
	},
	{
		id: "gpt-5-mini",
		name: "GPT-5 Mini",
		description:
			"Compact GPT-5 variant with reasoning and vision at reduced cost.",
		family: "openai",
		releasedAt: new Date("2025-08-01"),
		providers: [
			{
				providerId: "openai",
				modelName: "gpt-5-mini",
				inputPrice: 0.25 / 1e6,
				outputPrice: 2 / 1e6,
				cachedInputPrice: 0.025 / 1e6,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 128000,
				reasoning: true,
				streaming: true,
				vision: true,
				tools: true,
				webSearch: true,
				webSearchPrice: 0.01, // $10 per 1000 searches for reasoning models
				supportsResponsesApi: true,
				jsonOutputSchema: true,
				supportedParameters: [
					"temperature",
					"top_p",
					"frequency_penalty",
					"presence_penalty",
					"response_format",
					"tools",
					"tool_choice",
				],
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "kiwillm-free-ai-hub",
				modelName: "openai/gpt-5-mini",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 128000,
				reasoning: true,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
				jsonOutputSchema: true,
			},
			{
				test: "skip",
				providerId: "azure",
				stability: "unstable" as const,
				modelName: "gpt-5-mini",
				inputPrice: 0.25 / 1e6,
				outputPrice: 2 / 1e6,
				cachedInputPrice: 0.025 / 1e6,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 128000,
				reasoning: true,
				supportsResponsesApi: true,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutputSchema: true,
				supportedParameters: [
					"temperature",
					"top_p",
					"frequency_penalty",
					"presence_penalty",
					"response_format",
					"tools",
					"tool_choice",
				],
				jsonOutput: true,
			},
		],
	},
	{
		id: "gpt-5-nano",
		name: "GPT-5 Nano",
		description:
			"Ultra-efficient GPT-5 variant for high-volume applications with reasoning support.",
		family: "openai",
		releasedAt: new Date("2025-08-01"),
		providers: [
			{
				providerId: "openai",
				modelName: "gpt-5-nano",
				inputPrice: 0.05 / 1e6,
				outputPrice: 0.4 / 1e6,
				cachedInputPrice: 0.005 / 1e6,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 128000,
				reasoning: true,
				streaming: true,
				vision: false,
				tools: true,
				webSearch: true,
				webSearchPrice: 0.01, // $10 per 1000 searches for reasoning models
				supportsResponsesApi: true,
				jsonOutputSchema: true,
				supportedParameters: [
					"temperature",
					"top_p",
					"frequency_penalty",
					"presence_penalty",
					"response_format",
					"tools",
					"tool_choice",
				],
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "kiwillm-free-ai-hub",
				modelName: "openai/gpt-5-nano",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 128000,
				reasoning: true,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
				jsonOutputSchema: true,
			},
			{
				test: "skip",
				providerId: "azure",
				stability: "unstable" as const,
				modelName: "gpt-5-nano",
				inputPrice: 0.05 / 1e6,
				outputPrice: 0.4 / 1e6,
				cachedInputPrice: 0.005 / 1e6,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 128000,
				reasoning: true,
				supportsResponsesApi: true,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutputSchema: true,
				supportedParameters: [
					"temperature",
					"top_p",
					"frequency_penalty",
					"presence_penalty",
					"response_format",
					"tools",
					"tool_choice",
				],
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "kiwillm-gpt-oss-worker",
				modelName: "gpt-5-nano",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 128000,
				reasoning: true,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutputSchema: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "gpt-5-chat-latest",
		name: "GPT-5 Chat Latest",
		description:
			"GPT-5 optimized for conversational interactions without tool calling.",
		family: "openai",
		releasedAt: new Date("2025-08-01"),
		providers: [
			{
				providerId: "openai",
				modelName: "gpt-5-chat-latest",
				inputPrice: 1.25 / 1e6,
				outputPrice: 10.0 / 1e6,
				cachedInputPrice: 0.125 / 1e6,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 128000,
				streaming: true,
				vision: true,
				tools: false,
				jsonOutputSchema: true,
				supportedParameters: [
					"temperature",
					"top_p",
					"frequency_penalty",
					"presence_penalty",
					"response_format",
				],
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "kiwillm-free-ai-hub",
				modelName: "openai/gpt-5-chat",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 128000,
				streaming: true,
				vision: true,
				tools: false,
				jsonOutput: true,
				jsonOutputSchema: true,
			},
		],
	},
	{
		id: "gpt-5.1",
		name: "GPT-5.1",
		description:
			"Iterative improvement on GPT-5 with enhanced reasoning and tool support.",
		family: "openai",
		releasedAt: new Date("2025-11-01"),
		providers: [
			{
				providerId: "openai",
				modelName: "gpt-5.1",
				inputPrice: 1.25 / 1e6,
				outputPrice: 10.0 / 1e6,
				cachedInputPrice: 0.125 / 1e6,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 128000,
				streaming: true,
				vision: true,
				tools: true,
				webSearch: true,
				webSearchPrice: 0.01, // $10 per 1000 searches for reasoning models
				reasoning: true,
				reasoningOutput: "omit",
				supportsResponsesApi: true,
				jsonOutputSchema: true,
				supportedParameters: [
					"temperature",
					"top_p",
					"frequency_penalty",
					"presence_penalty",
					"response_format",
				],
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "azure",
				modelName: "gpt-5.1",
				inputPrice: 1.25 / 1e6,
				outputPrice: 10.0 / 1e6,
				cachedInputPrice: 0.125 / 1e6,
				discount: 0.3,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 128000,
				streaming: true,
				vision: true,
				tools: true,
				reasoning: true,
				supportsResponsesApi: true,
				jsonOutputSchema: true,
				supportedParameters: [
					"temperature",
					"top_p",
					"frequency_penalty",
					"presence_penalty",
					"response_format",
				],
				jsonOutput: true,
			},
		],
	},
	{
		id: "gpt-5-pro",
		name: "GPT-5 Pro",
		description:
			"Premium GPT-5 tier with extended output limits and advanced reasoning for complex tasks.",
		family: "openai",
		releasedAt: new Date("2025-08-01"),
		providers: [
			{
				test: "skip",
				providerId: "openai",
				modelName: "gpt-5-pro",
				inputPrice: 15 / 1e6,
				outputPrice: 120.0 / 1e6,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 272000,
				streaming: true,
				reasoning: true,
				reasoningOutput: "omit",
				vision: true,
				tools: true,
				webSearch: true,
				webSearchPrice: 0.01, // $10 per 1000 searches for reasoning models
				supportsResponsesApi: true,
				jsonOutputSchema: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "gpt-5.1-codex",
		name: "GPT-5.1 Codex",
		description:
			"GPT-5.1 specialized for code generation and software development tasks.",
		family: "openai",
		releasedAt: new Date("2025-11-13"),
		providers: [
			{
				providerId: "openai",
				modelName: "gpt-5.1-codex",
				inputPrice: 1.25 / 1e6,
				outputPrice: 10 / 1e6,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 272000,
				streaming: true,
				reasoning: true,
				reasoningOutput: "omit",
				vision: true,
				tools: true,
				webSearch: true,
				webSearchPrice: 0.01, // $10 per 1000 searches for reasoning models
				supportsResponsesApi: true,
				jsonOutputSchema: false,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "azure",
				stability: "unstable" as const,
				modelName: "gpt-5.1-codex",
				inputPrice: 1.25 / 1e6,
				outputPrice: 10 / 1e6,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 272000,
				streaming: true,
				reasoning: true,
				vision: true,
				tools: true,
				supportsResponsesApi: true,
				jsonOutputSchema: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "gpt-5.1-codex-mini",
		name: "GPT-5.1 Codex mini",
		description:
			"Lightweight code-focused model for efficient software development workflows.",
		family: "openai",
		releasedAt: new Date("2025-11-12"),
		providers: [
			{
				providerId: "openai",
				modelName: "gpt-5.1-codex-mini",
				inputPrice: 0.25 / 1e6,
				outputPrice: 2 / 1e6,
				cachedInputPrice: 0.025 / 1e6,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 128000,
				streaming: true,
				reasoning: true,
				reasoningOutput: "omit",
				vision: true,
				tools: true,
				webSearch: true,
				webSearchPrice: 0.01, // $10 per 1000 searches for reasoning models
				supportsResponsesApi: true,
				jsonOutputSchema: false,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "kiwillm-free-ai-hub",
				modelName: "openai/gpt-5.1-codex-mini",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 128000,
				streaming: true,
				reasoning: true,
				reasoningOutput: "omit",
				vision: true,
				tools: true,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "azure",
				stability: "unstable" as const,
				modelName: "gpt-5.1-codex-mini",
				inputPrice: 0.25 / 1e6,
				outputPrice: 2 / 1e6,
				cachedInputPrice: 0.025 / 1e6,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 128000,
				streaming: true,
				reasoning: true,
				vision: true,
				tools: true,
				supportsResponsesApi: true,
				jsonOutputSchema: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "gpt-5.2",
		name: "GPT-5.2",
		description: "Latest GPT-5 model with enhanced reasoning and tool support.",
		family: "openai",
		releasedAt: new Date("2025-12-11"),
		providers: [
			{
				providerId: "openai",
				modelName: "gpt-5.2",
				inputPrice: 1.75 / 1e6,
				outputPrice: 14.0 / 1e6,
				cachedInputPrice: 0.175 / 1e6,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 128000,
				streaming: true,
				vision: true,
				tools: true,
				webSearch: true,
				webSearchPrice: 0.01, // $10 per 1000 searches for reasoning models
				reasoning: true,
				reasoningOutput: "omit",
				supportsResponsesApi: true,
				jsonOutputSchema: true,
				supportedParameters: [
					"temperature",
					"top_p",
					"frequency_penalty",
					"presence_penalty",
					"response_format",
				],
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "kiwillm-free-ai-hub",
				modelName: "openai/gpt-5.2",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 128000,
				streaming: true,
				vision: true,
				tools: true,
				webSearch: true,
				reasoning: true,
				reasoningOutput: "omit",
				jsonOutput: true,
				jsonOutputSchema: true,
			},
			{
				test: "skip",
				providerId: "azure",
				modelName: "gpt-5.2",
				inputPrice: 1.75 / 1e6,
				outputPrice: 14.0 / 1e6,
				cachedInputPrice: 0.175 / 1e6,
				discount: 0.3,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 128000,
				streaming: true,
				vision: true,
				tools: true,
				reasoning: true,
				supportsResponsesApi: true,
				jsonOutputSchema: true,
				supportedParameters: [
					"temperature",
					"top_p",
					"frequency_penalty",
					"presence_penalty",
					"response_format",
				],
				jsonOutput: true,
			},
		],
	},
	{
		id: "gpt-5.2-pro",
		name: "GPT-5.2 Pro",
		description:
			"Premium GPT-5.2 model with extended output limits and advanced reasoning for complex tasks.",
		family: "openai",
		releasedAt: new Date("2025-12-11"),
		providers: [
			{
				providerId: "openai",
				modelName: "gpt-5.2-pro",
				inputPrice: 21.0 / 1e6,
				outputPrice: 168.0 / 1e6,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 272000,
				streaming: true,
				reasoning: true,
				reasoningOutput: "omit",
				vision: true,
				tools: true,
				webSearch: true,
				webSearchPrice: 0.01, // $10 per 1000 searches for reasoning models
				supportsResponsesApi: true,
				jsonOutputSchema: false,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "azure",
				stability: "unstable" as const,
				modelName: "gpt-5.2-pro",
				inputPrice: 21.0 / 1e6,
				outputPrice: 168.0 / 1e6,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 272000,
				streaming: true,
				reasoning: true,
				vision: true,
				tools: true,
				supportsResponsesApi: true,
				jsonOutputSchema: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "gpt-5.2-chat-latest",
		name: "GPT-5.2 Chat",
		description:
			"GPT-5.2 Chat is the ChatGPT production snapshot for chat use. Use it to try the latest chat-focused updates.",
		family: "openai",
		releasedAt: new Date("2025-12-11"),
		providers: [
			{
				providerId: "openai",
				modelName: "gpt-5.2-chat-latest",
				inputPrice: 1.75 / 1e6,
				outputPrice: 14.0 / 1e6,
				cachedInputPrice: 0.175 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: 16400,
				streaming: true,
				reasoning: true,
				reasoningOutput: "omit",
				vision: true,
				tools: true,
				webSearch: true,
				webSearchPrice: 0.01, // $10 per 1000 searches for reasoning models
				supportsResponsesApi: true,
				jsonOutputSchema: false,
				jsonOutput: false,
			},
			{
				test: "skip",
				providerId: "kiwillm-free-ai-hub",
				modelName: "openai/gpt-5.2-chat",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: 16400,
				streaming: true,
				reasoning: true,
				reasoningOutput: "omit",
				vision: true,
				tools: true,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "azure",
				stability: "unstable" as const,
				modelName: "gpt-5.2-chat-latest",
				inputPrice: 1.75 / 1e6,
				outputPrice: 14.0 / 1e6,
				cachedInputPrice: 0.175 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: 16400,
				streaming: true,
				reasoning: true,
				vision: true,
				tools: true,
				supportsResponsesApi: true,
				jsonOutputSchema: false,
				jsonOutput: false,
			},
		],
	},
	{
		id: "gpt-5.4",
		name: "GPT-5.4",
		description:
			"Most capable model for complex professional work with reasoning support.",
		family: "openai",
		releasedAt: new Date("2026-03-06"),
		providers: [
			{
				providerId: "openai",
				modelName: "gpt-5.4",
				inputPrice: 2.5 / 1e6,
				outputPrice: 15.0 / 1e6,
				cachedInputPrice: 0.25 / 1e6,
				requestPrice: 0,
				contextSize: 1050000,
				maxOutput: 128000,
				streaming: true,
				vision: true,
				tools: true,
				webSearch: true,
				webSearchPrice: 0.01,
				reasoning: true,
				reasoningOutput: "omit",
				supportsResponsesApi: true,
				jsonOutputSchema: true,
				supportedParameters: [
					"temperature",
					"top_p",
					"frequency_penalty",
					"presence_penalty",
					"response_format",
				],
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "kiwillm-free-ai-hub",
				modelName: "openai/gpt-5.4",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 1050000,
				maxOutput: 128000,
				streaming: true,
				vision: true,
				tools: true,
				webSearch: true,
				reasoning: true,
				reasoningOutput: "omit",
				jsonOutput: true,
				jsonOutputSchema: true,
			},
			{
				providerId: "azure",
				modelName: "gpt-5.4",
				inputPrice: 2.5 / 1e6,
				outputPrice: 15.0 / 1e6,
				cachedInputPrice: 0.25 / 1e6,
				discount: 0.3,
				requestPrice: 0,
				contextSize: 1050000,
				maxOutput: 128000,
				streaming: true,
				vision: true,
				tools: true,
				webSearch: true,
				webSearchPrice: 0.01,
				reasoning: true,
				reasoningOutput: "omit",
				supportsResponsesApi: true,
				jsonOutputSchema: true,
				supportedParameters: [
					"temperature",
					"top_p",
					"frequency_penalty",
					"presence_penalty",
					"response_format",
				],
				jsonOutput: true,
			},
		],
	},
	{
		id: "gpt-5.4-pro",
		name: "GPT-5.4 Pro",
		description:
			"Version of GPT-5.4 that uses more compute for smarter and more precise responses.",
		family: "openai",
		releasedAt: new Date("2026-03-01"),
		providers: [
			{
				providerId: "openai",
				test: "skip",
				modelName: "gpt-5.4-pro",
				inputPrice: 30.0 / 1e6,
				outputPrice: 180.0 / 1e6,
				discount: 0.3,
				requestPrice: 0,
				contextSize: 1050000,
				maxOutput: 128000,
				streaming: true,
				reasoning: true,
				reasoningOutput: "omit",
				vision: true,
				tools: true,
				webSearch: true,
				webSearchPrice: 0.01,
				supportsResponsesApi: true,
				jsonOutputSchema: false,
				jsonOutput: true,
			},
			{
				providerId: "azure",
				test: "skip",
				modelName: "gpt-5.4-pro",
				inputPrice: 30.0 / 1e6,
				outputPrice: 180.0 / 1e6,
				requestPrice: 0,
				contextSize: 1050000,
				maxOutput: 128000,
				streaming: true,
				reasoning: true,
				reasoningOutput: "omit",
				vision: true,
				tools: true,
				webSearch: true,
				webSearchPrice: 0.01,
				supportsResponsesApi: true,
				jsonOutputSchema: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "gpt-5.2-codex",
		name: "GPT-5.2 Codex",
		description:
			"Upgraded codex model optimized for software engineering and agentic coding workflows with steerable reasoning.",
		family: "openai",
		releasedAt: new Date("2026-01-14"),
		providers: [
			{
				providerId: "openai",
				modelName: "gpt-5.2-codex",
				inputPrice: 1.75 / 1e6,
				outputPrice: 14.0 / 1e6,
				cachedInputPrice: 0.175 / 1e6,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 128000,
				streaming: true,
				reasoning: true,
				reasoningOutput: "omit",
				vision: true,
				tools: true,
				webSearch: true,
				webSearchPrice: 0.01,
				supportsResponsesApi: true,
				jsonOutputSchema: false,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "kiwillm-free-ai-hub",
				modelName: "openai/gpt-5.2-codex",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 128000,
				streaming: true,
				reasoning: true,
				reasoningOutput: "omit",
				vision: true,
				tools: true,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "azure",
				stability: "unstable" as const,
				modelName: "gpt-5.2-codex",
				inputPrice: 1.75 / 1e6,
				outputPrice: 14.0 / 1e6,
				cachedInputPrice: 0.175 / 1e6,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 128000,
				streaming: true,
				reasoning: true,
				vision: true,
				tools: true,
				supportsResponsesApi: true,
				jsonOutputSchema: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "gpt-5.3-codex",
		name: "GPT-5.3 Codex",
		description:
			"Most advanced agentic coding model combining frontier coding performance with broader reasoning capabilities.",
		family: "openai",
		releasedAt: new Date("2026-02-24"),
		providers: [
			{
				providerId: "openai",
				modelName: "gpt-5.3-codex",
				inputPrice: 1.75 / 1e6,
				outputPrice: 14.0 / 1e6,
				cachedInputPrice: 0.175 / 1e6,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 128000,
				streaming: true,
				reasoning: true,
				reasoningOutput: "omit",
				vision: true,
				tools: true,
				webSearch: true,
				webSearchPrice: 0.01,
				supportsResponsesApi: true,
				jsonOutputSchema: false,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "kiwillm-free-ai-hub",
				modelName: "openai/gpt-5.3-codex",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 128000,
				streaming: true,
				reasoning: true,
				reasoningOutput: "omit",
				vision: true,
				tools: true,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "azure",
				stability: "unstable" as const,
				modelName: "gpt-5.3-codex",
				inputPrice: 1.75 / 1e6,
				outputPrice: 14.0 / 1e6,
				cachedInputPrice: 0.175 / 1e6,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 128000,
				streaming: true,
				reasoning: true,
				vision: true,
				tools: true,
				supportsResponsesApi: true,
				jsonOutputSchema: false,
				jsonOutput: true,
			},
		],
	},
	{
		id: "gpt-5.3-chat-latest",
		name: "GPT-5.3 Chat",
		description:
			"GPT-5.3 Chat delivers smoother conversations with better accuracy and fewer unnecessary refusals.",
		family: "openai",
		releasedAt: new Date("2026-03-03"),
		providers: [
			{
				providerId: "openai",
				modelName: "gpt-5.3-chat-latest",
				inputPrice: 1.75 / 1e6,
				outputPrice: 14.0 / 1e6,
				cachedInputPrice: 0.175 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: 16384,
				streaming: true,
				reasoning: true,
				reasoningOutput: "omit",
				vision: true,
				tools: true,
				webSearch: true,
				webSearchPrice: 0.01,
				supportsResponsesApi: true,
				jsonOutputSchema: false,
				jsonOutput: false,
			},
			{
				test: "skip",
				providerId: "kiwillm-free-ai-hub",
				modelName: "openai/gpt-5.3-chat",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: 16384,
				streaming: true,
				reasoning: true,
				reasoningOutput: "omit",
				vision: true,
				tools: true,
				jsonOutput: true,
			},
			{
				test: "skip",
				providerId: "azure",
				stability: "unstable" as const,
				modelName: "gpt-5.3-chat-latest",
				inputPrice: 1.75 / 1e6,
				outputPrice: 14.0 / 1e6,
				cachedInputPrice: 0.175 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: 16384,
				streaming: true,
				reasoning: true,
				vision: true,
				tools: true,
				supportsResponsesApi: true,
				jsonOutputSchema: false,
				jsonOutput: false,
			},
		],
	},
	{
		id: "gpt-5-codex",
		name: "GPT-5 Codex",
		description:
			"GPT-5 coding-focused model exposed through the KiwiLLM free AI hub worker.",
		family: "openai",
		providers: [
			{
				test: "skip",
				providerId: "kiwillm-free-ai-hub",
				modelName: "openai/gpt-5-codex",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 128000,
				streaming: true,
				reasoning: true,
				reasoningOutput: "omit",
				vision: true,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "gpt-5-image",
		name: "GPT-5 Image",
		description:
			"GPT-5 image-capable model exposed through the KiwiLLM free AI hub worker.",
		family: "openai",
		output: ["text", "image"],
		providers: [
			{
				test: "skip",
				providerId: "kiwillm-free-ai-hub",
				modelName: "openai/gpt-5-image",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 128000,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "gpt-5-image-mini",
		name: "GPT-5 Image Mini",
		description:
			"Compact GPT-5 image-capable model exposed through the KiwiLLM free AI hub worker.",
		family: "openai",
		output: ["text", "image"],
		providers: [
			{
				test: "skip",
				providerId: "kiwillm-free-ai-hub",
				modelName: "openai/gpt-5-image-mini",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 128000,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "gpt-5.1-codex-max",
		name: "GPT-5.1 Codex Max",
		description:
			"Higher-capability GPT-5.1 Codex variant exposed through the KiwiLLM free AI hub worker.",
		family: "openai",
		providers: [
			{
				test: "skip",
				providerId: "kiwillm-free-ai-hub",
				modelName: "openai/gpt-5.1-codex-max",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 400000,
				maxOutput: 128000,
				streaming: true,
				reasoning: true,
				reasoningOutput: "omit",
				vision: true,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "gpt-5.4-mini",
		name: "GPT-5.4 Mini",
		description:
			"Compact GPT-5.4 variant exposed through the KiwiLLM free AI hub worker.",
		family: "openai",
		providers: [
			{
				test: "skip",
				providerId: "kiwillm-free-ai-hub",
				modelName: "openai/gpt-5.4-mini",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 1050000,
				maxOutput: 128000,
				streaming: true,
				reasoning: true,
				reasoningOutput: "omit",
				vision: true,
				tools: true,
				jsonOutput: true,
				jsonOutputSchema: true,
			},
		],
	},
	{
		id: "gpt-5.4-nano",
		name: "GPT-5.4 Nano",
		description:
			"Ultra-light GPT-5.4 variant exposed through the KiwiLLM free AI hub worker.",
		family: "openai",
		providers: [
			{
				test: "skip",
				providerId: "kiwillm-free-ai-hub",
				modelName: "openai/gpt-5.4-nano",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 1050000,
				maxOutput: 128000,
				streaming: true,
				reasoning: true,
				reasoningOutput: "omit",
				vision: true,
				tools: true,
				jsonOutput: true,
				jsonOutputSchema: true,
			},
		],
	},
] as const satisfies ModelDefinition[];
