import type { ModelDefinition } from "@/models.js";

export const perplexityModels = [
	{
		id: "sonar-reasoning-pro",
		name: "Sonar Reasoning Pro",
		description: "Perplexity's advanced reasoning model with web search.",
		family: "perplexity",
		releasedAt: new Date("2025-03-07"),
		providers: [
			{
				providerId: "perplexity",
				modelName: "sonar-reasoning-pro",
				inputPrice: 2 / 1e6,
				outputPrice: 8 / 1e6,
				requestPrice: 5.0 / 1000,
				imageInputPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				test: "skip",
				jsonOutput: false,
				jsonOutputSchema: true,
			},
		],
	},
	{
		id: "sonar-pro",
		name: "Sonar Pro",
		description: "Professional Sonar model with enhanced search capabilities.",
		family: "perplexity",
		releasedAt: new Date("2025-03-07"),
		providers: [
			{
				providerId: "perplexity",
				modelName: "sonar-pro",
				inputPrice: 3 / 1e6,
				outputPrice: 15 / 1e6,
				requestPrice: 5.0 / 1000,
				imageInputPrice: 0,
				contextSize: 200000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				test: "skip",
				jsonOutput: false,
				jsonOutputSchema: true,
			},
			{
				test: "skip",
				providerId: "kiwillm-n33-ai",
				modelName: "sonar-pro",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
				jsonOutputSchema: true,
			},
		],
	},
	{
		id: "sonar",
		name: "Sonar",
		description: "Standard Sonar model for search-augmented generation.",
		family: "perplexity",
		releasedAt: new Date("2025-01-01"),
		providers: [
			{
				providerId: "perplexity",
				modelName: "sonar",
				inputPrice: 1 / 1e6,
				outputPrice: 1 / 1e6,
				requestPrice: 5.0 / 1000,
				imageInputPrice: 0,
				contextSize: 130000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				test: "skip",
				jsonOutput: false,
				jsonOutputSchema: true,
			},
			{
				test: "skip",
				providerId: "kiwillm-n33-ai",
				modelName: "sonar",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 130000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: true,
				jsonOutputSchema: true,
			},
		],
	},
] as const satisfies ModelDefinition[];
